"""Where uploaded files are kept. Services talk to a FileStorage; which one is used is a
FastAPI dependency (like the email sender), so tests use a temporary folder.

Dev uses LocalFileStorage (a folder outside the repo, settings.upload_dir). Production
swaps in UK-hosted object storage behind the same interface (launch phase L3).

Keys are always generated by us (`storage_key`), never taken from a filename the user
sent, and every key is checked again before touching the disk, so a key can never point
outside the storage folder.
"""

import hashlib
import os
import re
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import BinaryIO, Protocol

from app.core.config import get_settings
from app.models.imports import FILE_SUFFIXES

CHUNK_BYTES = 1024 * 1024
_UUID = r"[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
_KEY = re.compile(rf"^{_UUID}/{_UUID}\.(csv|xlsx)$")


class InvalidStorageKeyError(ValueError):
    """A key that storage_key() could not have produced: a bug or tampering."""


class FileTooLargeError(ValueError):
    def __init__(self, max_bytes: int) -> None:
        super().__init__(f"File is larger than {max_bytes} bytes")
        self.max_bytes = max_bytes


@dataclass(frozen=True)
class StoredFile:
    key: str
    size_bytes: int
    sha256: str


def storage_key(organization_id: uuid.UUID, import_id: uuid.UUID, source: str) -> str:
    """`{organization_id}/{import_id}.csv|.xlsx`: one folder per business."""
    return check_key(f"{organization_id}/{import_id}{FILE_SUFFIXES[source]}")


def check_key(key: str) -> str:
    if not _KEY.fullmatch(key):
        raise InvalidStorageKeyError(f"Invalid storage key: {key!r}")
    return key


class FileStorage(Protocol):
    def save(self, key: str, stream: BinaryIO, *, max_bytes: int) -> StoredFile: ...

    def open(self, key: str) -> BinaryIO: ...

    def exists(self, key: str) -> bool: ...

    def delete(self, key: str) -> bool: ...


class LocalFileStorage:
    """Files on local disk under `root`. Development and tests only."""

    def __init__(self, root: str | Path) -> None:
        self.root = Path(root).resolve()

    def _path(self, key: str) -> Path:
        path = (self.root / check_key(key)).resolve()
        if not path.is_relative_to(self.root):  # belt and braces on top of check_key
            raise InvalidStorageKeyError(f"Invalid storage key: {key!r}")
        return path

    def save(self, key: str, stream: BinaryIO, *, max_bytes: int) -> StoredFile:
        """Stream to disk, measuring and fingerprinting as we go. Stops as soon as the
        file passes max_bytes; a half-written file is never left behind."""
        path = self._path(key)
        if path.exists():
            raise FileExistsError(f"Refusing to overwrite {key}")
        path.parent.mkdir(parents=True, exist_ok=True)
        partial = path.with_name(f".{path.name}.{uuid.uuid4().hex}.partial")
        digest, size = hashlib.sha256(), 0
        try:
            with partial.open("xb") as out:
                while chunk := stream.read(CHUNK_BYTES):
                    size += len(chunk)
                    if size > max_bytes:
                        raise FileTooLargeError(max_bytes)
                    digest.update(chunk)
                    out.write(chunk)
            os.replace(partial, path)
        except BaseException:
            partial.unlink(missing_ok=True)
            raise
        return StoredFile(key=key, size_bytes=size, sha256=digest.hexdigest())

    def open(self, key: str) -> BinaryIO:
        return self._path(key).open("rb")

    def exists(self, key: str) -> bool:
        return self._path(key).is_file()

    def delete(self, key: str) -> bool:
        """True if a file was deleted, False if it was already gone."""
        path = self._path(key)
        try:
            path.unlink()
        except FileNotFoundError:
            return False
        return True


def get_file_storage() -> FileStorage:
    """FastAPI dependency. Tests override this with a temporary folder."""
    return LocalFileStorage(get_settings().upload_dir)
