"""action tables

Revision ID: 86f3a18e04cb
Revises: d41a7c0e9b35
Create Date: 2026-10-05 08:47:30.929592
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "86f3a18e04cb"
down_revision: str | None = "d41a7c0e9b35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "interventions",
        sa.Column("recommendation_id", sa.Uuid(), nullable=True),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("library_id", sa.Uuid(), nullable=True),
        sa.Column("library_code", sa.String(length=60), nullable=True),
        sa.Column("kpi_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=15), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("original_title", sa.String(length=200), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("target_label", sa.String(length=200), nullable=True),
        sa.Column("expected_impact_value", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("expected_impact_unit", sa.String(length=10), nullable=True),
        sa.Column("baseline_period", sa.Date(), nullable=True),
        sa.Column("baseline_value", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("recommendation_score", sa.Integer(), nullable=True),
        sa.Column("rules_version", sa.String(length=30), nullable=True),
        sa.Column(
            "basis",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("accepted_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('financial', 'sales', 'customer', 'marketing', 'inventory', 'operational')",
            name=op.f("ck_interventions_category_valid"),
        ),
        sa.CheckConstraint(
            "length(trim(title)) > 0", name=op.f("ck_interventions_title_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["accepted_by_user_id"],
            ["users.id"],
            name=op.f("fk_interventions_accepted_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["kpi_id"], ["kpi_definitions.id"], name=op.f("fk_interventions_kpi_id_kpi_definitions")
        ),
        sa.ForeignKeyConstraint(
            ["library_id"],
            ["intervention_library.id"],
            name=op.f("fk_interventions_library_id_intervention_library"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_interventions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interventions")),
        sa.UniqueConstraint("organization_id", "id", name="uq_interventions_org_id"),
    )
    op.create_index(
        "ix_interventions_org_accepted",
        "interventions",
        ["organization_id", "accepted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_interventions_organization_id"), "interventions", ["organization_id"], unique=False
    )
    op.create_table(
        "actions",
        sa.Column("intervention_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=15), nullable=False),
        sa.Column(
            "steps",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=25), nullable=False),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("approved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'completed') = (completed_at IS NOT NULL)",
            name=op.f("ck_actions_completed_has_time"),
        ),
        sa.CheckConstraint(
            "category IN ('financial', 'sales', 'customer', 'marketing', 'inventory', 'operational')",
            name=op.f("ck_actions_category_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'in_progress', 'partially_completed', 'completed', 'cancelled', 'overdue')",
            name=op.f("ck_actions_status_valid"),
        ),
        sa.CheckConstraint("length(trim(title)) > 0", name=op.f("ck_actions_title_not_blank")),
        sa.CheckConstraint(
            "start_date IS NULL OR target_date IS NULL OR target_date >= start_date",
            name=op.f("ck_actions_dates_in_order"),
        ),
        sa.ForeignKeyConstraint(
            ["approved_by_user_id"],
            ["users.id"],
            name=op.f("fk_actions_approved_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_actions_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "intervention_id"],
            ["interventions.organization_id", "interventions.id"],
            name=op.f("fk_actions_organization_id_interventions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_actions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id"],
            ["users.id"],
            name=op.f("fk_actions_owner_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_actions")),
        sa.UniqueConstraint("intervention_id", name="uq_actions_intervention"),
        sa.UniqueConstraint("organization_id", "id", name="uq_actions_org_id"),
    )
    op.create_index(
        "ix_actions_org_owner", "actions", ["organization_id", "owner_user_id"], unique=False
    )
    op.create_index("ix_actions_org_status", "actions", ["organization_id", "status"], unique=False)
    op.create_index(
        "ix_actions_org_target", "actions", ["organization_id", "target_date"], unique=False
    )
    op.create_index(
        op.f("ix_actions_organization_id"), "actions", ["organization_id"], unique=False
    )
    op.create_table(
        "action_evidence",
        sa.Column("action_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("url", sa.String(length=500), nullable=True),
        sa.Column("storage_key", sa.String(length=200), nullable=True),
        sa.Column("original_filename", sa.String(length=255), nullable=True),
        sa.Column("content_type", sa.String(length=100), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "kind <> 'file' OR storage_key IS NOT NULL",
            name=op.f("ck_action_evidence_file_has_key"),
        ),
        sa.CheckConstraint(
            "kind <> 'link' OR url IS NOT NULL", name=op.f("ck_action_evidence_link_has_url")
        ),
        sa.CheckConstraint(
            "kind IN ('note', 'link', 'file')", name=op.f("ck_action_evidence_kind_valid")
        ),
        sa.CheckConstraint(
            "length(trim(title)) > 0", name=op.f("ck_action_evidence_title_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "action_id"],
            ["actions.organization_id", "actions.id"],
            name=op.f("fk_action_evidence_organization_id_actions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_action_evidence_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_action_evidence_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_evidence")),
    )
    op.create_index(
        "ix_action_evidence_action", "action_evidence", ["action_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_action_evidence_organization_id"),
        "action_evidence",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "action_updates",
        sa.Column("action_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("from_status", sa.String(length=25), nullable=True),
        sa.Column("to_status", sa.String(length=25), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('created', 'approved', 'rejected', 'status', 'note', 'assignment', 'dates', 'modification', 'steps', 'evidence', 'overdue')",
            name=op.f("ck_action_updates_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "action_id"],
            ["actions.organization_id", "actions.id"],
            name=op.f("fk_action_updates_organization_id_actions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_action_updates_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_action_updates_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_action_updates")),
    )
    op.create_index(
        "ix_action_updates_action", "action_updates", ["action_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_action_updates_organization_id"),
        "action_updates",
        ["organization_id"],
        unique=False,
    )

    # A recommendation can now also be proposed (waiting for approval) or accepted (being done).
    op.drop_constraint(op.f("ck_recommendations_status_valid"), "recommendations", type_="check")
    op.create_check_constraint(
        op.f("ck_recommendations_status_valid"),
        "recommendations",
        "status IN ('open', 'no_action_needed', 'insufficient_evidence', 'dismissed', 'proposed', 'accepted')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(op.f("ck_recommendations_status_valid"), "recommendations", type_="check")
    op.create_check_constraint(
        op.f("ck_recommendations_status_valid"),
        "recommendations",
        "status IN ('open', 'no_action_needed', 'insufficient_evidence', 'dismissed')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_action_updates_organization_id"), table_name="action_updates")
    op.drop_index("ix_action_updates_action", table_name="action_updates")
    op.drop_table("action_updates")
    op.drop_index(op.f("ix_action_evidence_organization_id"), table_name="action_evidence")
    op.drop_index("ix_action_evidence_action", table_name="action_evidence")
    op.drop_table("action_evidence")
    op.drop_index(op.f("ix_actions_organization_id"), table_name="actions")
    op.drop_index("ix_actions_org_target", table_name="actions")
    op.drop_index("ix_actions_org_status", table_name="actions")
    op.drop_index("ix_actions_org_owner", table_name="actions")
    op.drop_table("actions")
    op.drop_index(op.f("ix_interventions_organization_id"), table_name="interventions")
    op.drop_index("ix_interventions_org_accepted", table_name="interventions")
    op.drop_table("interventions")
    # ### end Alembic commands ###
