"""report tables

Revision ID: 1b6ad17eb684
Revises: 5776bf64acb9
Create Date: 2026-10-09 10:28:44.633694
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "1b6ad17eb684"
down_revision: str | None = "5776bf64acb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("kind", sa.String(length=15), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("months", sa.SmallInteger(), server_default=sa.text("6"), nullable=False),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('monthly', 'health', 'kpi', 'outcomes')", name=op.f("ck_reports_kind_valid")
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_reports_name_not_blank")),
        sa.CheckConstraint("months BETWEEN 1 AND 24", name=op.f("ck_reports_months_range")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reports_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_reports_updated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
        sa.UniqueConstraint("organization_id", "id", name="uq_reports_org_id"),
        sa.UniqueConstraint("organization_id", "kind", name="uq_reports_kind"),
    )
    op.create_index(
        op.f("ix_reports_organization_id"), "reports", ["organization_id"], unique=False
    )
    op.create_table(
        "report_schedules",
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("frequency", sa.String(length=10), nullable=False),
        sa.Column("weekday", sa.SmallInteger(), nullable=True),
        sa.Column("day_of_month", sa.SmallInteger(), nullable=True),
        sa.Column(
            "recipients",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(frequency = 'weekly' AND weekday IS NOT NULL AND weekday BETWEEN 1 AND 7 AND day_of_month IS NULL) OR (frequency = 'monthly' AND day_of_month IS NOT NULL AND day_of_month BETWEEN 1 AND 28 AND weekday IS NULL)",
            name=op.f("ck_report_schedules_when_valid"),
        ),
        sa.CheckConstraint(
            "frequency IN ('weekly', 'monthly')", name=op.f("ck_report_schedules_frequency_valid")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_report_schedules_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "report_id"],
            ["reports.organization_id", "reports.id"],
            name=op.f("fk_report_schedules_organization_id_reports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_report_schedules_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_schedules")),
        sa.UniqueConstraint("organization_id", "id", name="uq_report_schedules_org_id"),
    )
    op.create_index(
        "ix_report_schedules_due", "report_schedules", ["enabled", "next_run_at"], unique=False
    )
    op.create_index(
        op.f("ix_report_schedules_organization_id"),
        "report_schedules",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "report_runs",
        sa.Column("report_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("schedule_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=15), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("trigger", sa.String(length=10), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rules_version", sa.String(length=30), nullable=False),
        sa.Column("generated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("emailed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "trigger IN ('manual', 'scheduled')", name=op.f("ck_report_runs_trigger_valid")
        ),
        sa.CheckConstraint(
            "period_end >= period_start", name=op.f("ck_report_runs_period_in_order")
        ),
        sa.ForeignKeyConstraint(
            ["generated_by_user_id"],
            ["users.id"],
            name=op.f("fk_report_runs_generated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "report_id"],
            ["reports.organization_id", "reports.id"],
            name=op.f("fk_report_runs_organization_id_reports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_report_runs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["report_schedules.id"],
            name=op.f("fk_report_runs_schedule_id_report_schedules"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_report_runs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_runs")),
    )
    op.create_index(
        op.f("ix_report_runs_organization_id"), "report_runs", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_report_runs_user",
        "report_runs",
        ["organization_id", "user_id", "generated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_report_runs_user", table_name="report_runs")
    op.drop_index(op.f("ix_report_runs_organization_id"), table_name="report_runs")
    op.drop_table("report_runs")
    op.drop_index(op.f("ix_report_schedules_organization_id"), table_name="report_schedules")
    op.drop_index("ix_report_schedules_due", table_name="report_schedules")
    op.drop_table("report_schedules")
    op.drop_index(op.f("ix_reports_organization_id"), table_name="reports")
    op.drop_table("reports")
    # ### end Alembic commands ###
