"""alert and notification tables

Revision ID: 5776bf64acb9
Revises: 244c43b07705
Create Date: 2026-10-05 22:31:07.562625
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5776bf64acb9"
down_revision: str | None = "244c43b07705"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_rules",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category <> 'security' OR enabled", name=op.f("ck_alert_rules_security_always_on")
        ),
        sa.CheckConstraint(
            "category IN ('sales', 'financial', 'customer', 'inventory', 'marketing', 'forecast', 'action', 'data', 'security')",
            name=op.f("ck_alert_rules_category_valid"),
        ),
        sa.CheckConstraint(
            "severity IN ('info', 'low', 'medium', 'high', 'critical')",
            name=op.f("ck_alert_rules_severity_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_alert_rules_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["users.id"],
            name=op.f("fk_alert_rules_updated_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_rules")),
        sa.UniqueConstraint("organization_id", "code", name="uq_alert_rules_code"),
    )
    op.create_index(
        op.f("ix_alert_rules_organization_id"), "alert_rules", ["organization_id"], unique=False
    )
    op.create_table(
        "alerts",
        sa.Column("rule_code", sa.String(length=40), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("kpi_category", sa.String(length=15), nullable=True),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("link", sa.String(length=200), nullable=True),
        sa.Column("dedupe_key", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=15), server_default="open", nullable=False),
        sa.Column("occurrences", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("acknowledged_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('sales', 'financial', 'customer', 'inventory', 'marketing', 'forecast', 'action', 'data', 'security')",
            name=op.f("ck_alerts_category_valid"),
        ),
        sa.CheckConstraint(
            "severity IN ('info', 'low', 'medium', 'high', 'critical')",
            name=op.f("ck_alerts_severity_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'acknowledged', 'resolved')", name=op.f("ck_alerts_status_valid")
        ),
        sa.CheckConstraint("length(trim(title)) > 0", name=op.f("ck_alerts_title_not_blank")),
        sa.CheckConstraint("occurrences >= 1", name=op.f("ck_alerts_occurrences_positive")),
        sa.ForeignKeyConstraint(
            ["acknowledged_by_user_id"],
            ["users.id"],
            name=op.f("fk_alerts_acknowledged_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_alerts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alerts")),
        sa.UniqueConstraint("organization_id", "id", name="uq_alerts_org_id"),
    )
    op.create_index(
        "ix_alerts_org_status",
        "alerts",
        ["organization_id", "status", "last_seen_at"],
        unique=False,
    )
    op.create_index(op.f("ix_alerts_organization_id"), "alerts", ["organization_id"], unique=False)
    op.create_index(
        "uq_alerts_open_dedupe",
        "alerts",
        ["organization_id", "dedupe_key"],
        unique=True,
        postgresql_where=sa.text("status <> 'resolved'"),
    )
    op.create_table(
        "alert_events",
        sa.Column("alert_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=15), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('raised', 'repeated', 'acknowledged', 'resolved', 'reopened')",
            name=op.f("ck_alert_events_kind_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "alert_id"],
            ["alerts.organization_id", "alerts.id"],
            name=op.f("fk_alert_events_organization_id_alerts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_alert_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_alert_events_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_alert_events")),
    )
    op.create_index(
        "ix_alert_events_alert", "alert_events", ["alert_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_alert_events_organization_id"), "alert_events", ["organization_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("alert_id", sa.Uuid(), nullable=True),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("link", sa.String(length=200), nullable=True),
        sa.Column("in_app", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("email_status", sa.String(length=10), server_default="none", nullable=False),
        sa.Column("email_after", sa.DateTime(timezone=True), nullable=True),
        sa.Column("email_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "category IN ('sales', 'financial', 'customer', 'inventory', 'marketing', 'forecast', 'action', 'data', 'security')",
            name=op.f("ck_notifications_category_valid"),
        ),
        sa.CheckConstraint(
            "email_status IN ('none', 'pending', 'sent', 'failed')",
            name=op.f("ck_notifications_email_status_valid"),
        ),
        sa.CheckConstraint(
            "severity IN ('info', 'low', 'medium', 'high', 'critical')",
            name=op.f("ck_notifications_severity_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "alert_id"],
            ["alerts.organization_id", "alerts.id"],
            name=op.f("fk_notifications_organization_id_alerts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_notifications_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_email_due", "notifications", ["email_status", "email_after"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_organization_id"), "notifications", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_notifications_user",
        "notifications",
        ["organization_id", "user_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_notifications_user", table_name="notifications")
    op.drop_index(op.f("ix_notifications_organization_id"), table_name="notifications")
    op.drop_index("ix_notifications_email_due", table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_alert_events_organization_id"), table_name="alert_events")
    op.drop_index("ix_alert_events_alert", table_name="alert_events")
    op.drop_table("alert_events")
    op.drop_index(
        "uq_alerts_open_dedupe",
        table_name="alerts",
        postgresql_where=sa.text("status <> 'resolved'"),
    )
    op.drop_index(op.f("ix_alerts_organization_id"), table_name="alerts")
    op.drop_index("ix_alerts_org_status", table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_alert_rules_organization_id"), table_name="alert_rules")
    op.drop_table("alert_rules")
    # ### end Alembic commands ###
