"""business list items

Revision ID: 8458ef156a00
Revises: 032403888c06
Create Date: 2026-09-26 11:35:29.810534
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8458ef156a00"
down_revision: str | None = "032403888c06"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "business_list_items",
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), nullable=True),
        sa.Column("is_cost_of_sales", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind = 'cost_category' OR is_cost_of_sales IS NULL",
            name=op.f("ck_business_list_items_cost_of_sales_only_costs"),
        ),
        sa.CheckConstraint(
            "kind IN ('offering', 'sales_channel', 'customer_type', 'cost_category')",
            name=op.f("ck_business_list_items_kind_valid"),
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0", name=op.f("ck_business_list_items_name_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_business_list_items_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_list_items")),
    )
    op.create_index(
        op.f("ix_business_list_items_organization_id"),
        "business_list_items",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "uq_business_list_items_name",
        "business_list_items",
        ["organization_id", "kind", sa.literal_column("lower(name)")],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_business_list_items_name", table_name="business_list_items")
    op.drop_index(op.f("ix_business_list_items_organization_id"), table_name="business_list_items")
    op.drop_table("business_list_items")
    # ### end Alembic commands ###
