"""diagnostic tables

Revision ID: f8ea47f386e8
Revises: 9b3e4d7a2c18
Create Date: 2026-10-03 10:19:32.904071
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f8ea47f386e8"
down_revision: str | None = "9b3e4d7a2c18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "detection_events",
        sa.Column("kpi_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=20), server_default="material_change", nullable=False),
        sa.Column("granularity", sa.String(length=10), server_default="month", nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("direction", sa.String(length=5), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("effect", sa.String(length=10), nullable=False),
        sa.Column("value", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("reference_value", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("change", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("change_unit", sa.String(length=10), nullable=False),
        sa.Column(
            "explained_by_season", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("data_quality", sa.SmallInteger(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=10), server_default="open", nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "change_unit IN ('percent', 'points')",
            name=op.f("ck_detection_events_change_unit_valid"),
        ),
        sa.CheckConstraint(
            "direction IN ('up', 'down')", name=op.f("ck_detection_events_direction_valid")
        ),
        sa.CheckConstraint(
            "effect IN ('good', 'bad', 'neutral')", name=op.f("ck_detection_events_effect_valid")
        ),
        sa.CheckConstraint(
            "granularity = 'month'", name=op.f("ck_detection_events_granularity_valid")
        ),
        sa.CheckConstraint(
            "kind IN ('material_change', 'anomaly')", name=op.f("ck_detection_events_kind_valid")
        ),
        sa.CheckConstraint(
            "severity IN ('notable', 'major')", name=op.f("ck_detection_events_severity_valid")
        ),
        sa.CheckConstraint(
            "status IN ('open', 'dismissed', 'diagnosed')",
            name=op.f("ck_detection_events_status_valid"),
        ),
        sa.CheckConstraint(
            "data_quality IS NULL OR data_quality BETWEEN 0 AND 100",
            name=op.f("ck_detection_events_quality_in_range"),
        ),
        sa.CheckConstraint(
            "length(trim(summary)) > 0", name=op.f("ck_detection_events_summary_not_blank")
        ),
        sa.CheckConstraint(
            "period_end >= period_start", name=op.f("ck_detection_events_period_in_order")
        ),
        sa.ForeignKeyConstraint(
            ["kpi_id"],
            ["kpi_definitions.id"],
            name=op.f("fk_detection_events_kpi_id_kpi_definitions"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_detection_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_detection_events")),
        sa.UniqueConstraint("organization_id", "id", name="uq_detection_events_org_id"),
        sa.UniqueConstraint(
            "organization_id",
            "kpi_id",
            "kind",
            "granularity",
            "period_start",
            name="uq_detection_events_kpi_period",
        ),
    )
    op.create_index("ix_detection_events_kpi", "detection_events", ["kpi_id"], unique=False)
    op.create_index(
        "ix_detection_events_org_period",
        "detection_events",
        ["organization_id", "period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_detection_events_organization_id"),
        "detection_events",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "diagnoses",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=25), nullable=False),
        sa.Column("headline", sa.String(length=300), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("confidence", sa.SmallInteger(), nullable=True),
        sa.Column("confidence_label", sa.String(length=15), nullable=False),
        sa.Column("diagnosed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'insufficient_evidence') = (confidence_label = 'insufficient')",
            name=op.f("ck_diagnoses_insufficient_matches_label"),
        ),
        sa.CheckConstraint(
            "confidence_label IN ('high', 'medium', 'low', 'insufficient')",
            name=op.f("ck_diagnoses_confidence_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('ready', 'insufficient_evidence')", name=op.f("ck_diagnoses_status_valid")
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 100",
            name=op.f("ck_diagnoses_confidence_in_range"),
        ),
        sa.CheckConstraint(
            "length(trim(headline)) > 0", name=op.f("ck_diagnoses_headline_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "event_id"],
            ["detection_events.organization_id", "detection_events.id"],
            name=op.f("fk_diagnoses_organization_id_detection_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_diagnoses_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diagnoses")),
        sa.UniqueConstraint("event_id", name="uq_diagnoses_event"),
        sa.UniqueConstraint("organization_id", "id", name="uq_diagnoses_org_id"),
    )
    op.create_index(
        op.f("ix_diagnoses_organization_id"), "diagnoses", ["organization_id"], unique=False
    )
    op.create_table(
        "diagnostic_evidence",
        sa.Column("diagnosis_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_type", sa.String(length=20), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("sort_order", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "evidence_type IN ('fact', 'statistical', 'ai_interpretation', 'insufficient')",
            name=op.f("ck_diagnostic_evidence_evidence_type_valid"),
        ),
        sa.CheckConstraint(
            "length(trim(statement)) > 0", name=op.f("ck_diagnostic_evidence_statement_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "diagnosis_id"],
            ["diagnoses.organization_id", "diagnoses.id"],
            name=op.f("fk_diagnostic_evidence_organization_id_diagnoses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_diagnostic_evidence_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_diagnostic_evidence")),
    )
    op.create_index(
        "ix_diagnostic_evidence_diagnosis",
        "diagnostic_evidence",
        ["diagnosis_id", "sort_order"],
        unique=False,
    )
    op.create_index(
        op.f("ix_diagnostic_evidence_organization_id"),
        "diagnostic_evidence",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_diagnostic_evidence_organization_id"), table_name="diagnostic_evidence")
    op.drop_index("ix_diagnostic_evidence_diagnosis", table_name="diagnostic_evidence")
    op.drop_table("diagnostic_evidence")
    op.drop_index(op.f("ix_diagnoses_organization_id"), table_name="diagnoses")
    op.drop_table("diagnoses")
    op.drop_index(op.f("ix_detection_events_organization_id"), table_name="detection_events")
    op.drop_index("ix_detection_events_org_period", table_name="detection_events")
    op.drop_index("ix_detection_events_kpi", table_name="detection_events")
    op.drop_table("detection_events")
    # ### end Alembic commands ###
