"""indexes for foreign key lookups

Revision ID: 1dc2737c9ab6
Revises: 5089674c18c9
Create Date: 2026-10-01 22:34:53.105790
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1dc2737c9ab6"
down_revision: str | None = "5089674c18c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_customers_org_type", "customers", ["organization_id", "customer_type_id"], unique=False
    )
    op.create_index(
        "ix_data_imports_org_source",
        "data_imports",
        ["organization_id", "data_source_id"],
        unique=False,
    )
    op.create_index(
        "ix_expenses_org_category",
        "expenses",
        ["organization_id", "cost_category_id"],
        unique=False,
    )
    op.create_index(
        "ix_expenses_org_supplier", "expenses", ["organization_id", "supplier_id"], unique=False
    )
    op.create_index(
        "ix_products_org_offering", "products", ["organization_id", "offering_id"], unique=False
    )
    op.create_index(
        "ix_sales_org_channel", "sales", ["organization_id", "sales_channel_id"], unique=False
    )
    op.create_index(
        "ix_sales_org_customer", "sales", ["organization_id", "customer_id"], unique=False
    )
    op.create_index(
        "ix_stock_movements_org_sale_line",
        "stock_movements",
        ["organization_id", "sale_line_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_stock_movements_org_sale_line", table_name="stock_movements")
    op.drop_index("ix_sales_org_customer", table_name="sales")
    op.drop_index("ix_sales_org_channel", table_name="sales")
    op.drop_index("ix_products_org_offering", table_name="products")
    op.drop_index("ix_expenses_org_supplier", table_name="expenses")
    op.drop_index("ix_expenses_org_category", table_name="expenses")
    op.drop_index("ix_data_imports_org_source", table_name="data_imports")
    op.drop_index("ix_customers_org_type", table_name="customers")
    # ### end Alembic commands ###
