"""import tracking tables

Revision ID: 6cb8930fcbc1
Revises: d431a4af5525
Create Date: 2026-09-29 00:22:08.084197
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "6cb8930fcbc1"
down_revision: str | None = "d431a4af5525"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_sources",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("dataset", sa.String(length=20), nullable=False),
        sa.Column(
            "column_mapping",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "options",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("last_imported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "dataset IN ('sales', 'expenses', 'customers', 'suppliers', 'products', 'stock_movements')",
            name=op.f("ck_data_sources_dataset_valid"),
        ),
        sa.CheckConstraint(
            "kind IN ('csv', 'excel', 'xero', 'shopify', 'woocommerce', 'google_analytics')",
            name=op.f("ck_data_sources_kind_valid"),
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_data_sources_name_not_blank")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_data_sources_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
        sa.UniqueConstraint("organization_id", "id", name="uq_data_sources_org_id"),
        sa.UniqueConstraint("organization_id", "name", name="uq_data_sources_name"),
    )
    op.create_index(
        op.f("ix_data_sources_organization_id"), "data_sources", ["organization_id"], unique=False
    )
    op.create_table(
        "data_imports",
        sa.Column("data_source_id", sa.Uuid(), nullable=True),
        sa.Column("source", sa.String(length=20), nullable=False),
        sa.Column("dataset", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="uploaded", nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("storage_key", sa.String(length=200), nullable=False),
        sa.Column("file_size_bytes", sa.Integer(), nullable=False),
        sa.Column("file_sha256", sa.String(length=64), nullable=False),
        sa.Column("sheet_name", sa.String(length=100), nullable=True),
        sa.Column("header_row", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column(
            "column_mapping",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "options",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("row_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("valid_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("invalid_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("duplicate_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("imported_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("uploaded_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("imported_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("undone_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("file_deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "dataset IN ('sales', 'expenses', 'customers', 'suppliers', 'products', 'stock_movements')",
            name=op.f("ck_data_imports_dataset_valid"),
        ),
        sa.CheckConstraint(
            "file_sha256 ~ '^[0-9a-f]{64}$'", name=op.f("ck_data_imports_file_sha256_format")
        ),
        sa.CheckConstraint(
            "source = 'excel' OR sheet_name IS NULL",
            name=op.f("ck_data_imports_sheet_only_for_excel"),
        ),
        sa.CheckConstraint("source IN ('csv', 'excel')", name=op.f("ck_data_imports_source_valid")),
        sa.CheckConstraint(
            "status <> 'undone' OR undone_at IS NOT NULL",
            name=op.f("ck_data_imports_undone_has_time"),
        ),
        sa.CheckConstraint(
            "status IN ('uploaded', 'mapped', 'validated', 'importing', 'imported', 'failed', 'undone')",
            name=op.f("ck_data_imports_status_valid"),
        ),
        sa.CheckConstraint(
            "status NOT IN ('imported', 'undone') OR imported_at IS NOT NULL",
            name=op.f("ck_data_imports_imported_has_time"),
        ),
        sa.CheckConstraint(
            "file_size_bytes >= 0", name=op.f("ck_data_imports_file_size_not_negative")
        ),
        sa.CheckConstraint("header_row >= 1", name=op.f("ck_data_imports_header_row_positive")),
        sa.CheckConstraint(
            "length(trim(original_filename)) > 0", name=op.f("ck_data_imports_filename_not_blank")
        ),
        sa.CheckConstraint(
            "row_count >= 0 AND valid_count >= 0 AND invalid_count >= 0 AND duplicate_count >= 0 AND imported_count >= 0",
            name=op.f("ck_data_imports_counts_not_negative"),
        ),
        sa.CheckConstraint(
            "valid_count + invalid_count + duplicate_count <= row_count",
            name=op.f("ck_data_imports_counts_add_up"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "data_source_id"],
            ["data_sources.organization_id", "data_sources.id"],
            name=op.f("fk_data_imports_organization_id_data_sources"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_data_imports_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by_user_id"],
            ["users.id"],
            name=op.f("fk_data_imports_uploaded_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_imports")),
        sa.UniqueConstraint("organization_id", "id", name="uq_data_imports_org_id"),
    )
    op.create_index(
        "ix_data_imports_org_created",
        "data_imports",
        ["organization_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_data_imports_org_sha256",
        "data_imports",
        ["organization_id", "file_sha256"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_imports_organization_id"), "data_imports", ["organization_id"], unique=False
    )
    op.create_table(
        "data_import_rows",
        sa.Column("import_id", sa.Uuid(), nullable=False),
        sa.Column("row_number", sa.Integer(), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=12), server_default="pending", nullable=False),
        sa.Column(
            "errors",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("target_table", sa.String(length=30), nullable=True),
        sa.Column("target_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status <> 'imported' OR target_id IS NOT NULL",
            name=op.f("ck_data_import_rows_imported_has_target"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'valid', 'invalid', 'duplicate', 'imported', 'skipped')",
            name=op.f("ck_data_import_rows_status_valid"),
        ),
        sa.CheckConstraint(
            "(target_table IS NULL) = (target_id IS NULL)",
            name=op.f("ck_data_import_rows_target_table_and_id_together"),
        ),
        sa.CheckConstraint("row_number >= 1", name=op.f("ck_data_import_rows_row_number_positive")),
        sa.ForeignKeyConstraint(
            ["organization_id", "import_id"],
            ["data_imports.organization_id", "data_imports.id"],
            name=op.f("fk_data_import_rows_organization_id_data_imports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_data_import_rows_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_import_rows")),
        sa.UniqueConstraint("import_id", "row_number", name="uq_data_import_rows_row"),
    )
    op.create_index(
        "ix_data_import_rows_import_status",
        "data_import_rows",
        ["import_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_import_rows_organization_id"),
        "data_import_rows",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "data_quality_issues",
        sa.Column("import_id", sa.Uuid(), nullable=True),
        sa.Column("dataset", sa.String(length=20), nullable=False),
        sa.Column("issue_type", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("affected_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "dataset IN ('sales', 'expenses', 'customers', 'suppliers', 'products', 'stock_movements')",
            name=op.f("ck_data_quality_issues_dataset_valid"),
        ),
        sa.CheckConstraint(
            "issue_type ~ '^[a-z][a-z_]*$'", name=op.f("ck_data_quality_issues_issue_type_format")
        ),
        sa.CheckConstraint(
            "severity IN ('info', 'warning', 'critical')",
            name=op.f("ck_data_quality_issues_severity_valid"),
        ),
        sa.CheckConstraint(
            "affected_count >= 0", name=op.f("ck_data_quality_issues_affected_count_not_negative")
        ),
        sa.CheckConstraint(
            "period_end >= period_start", name=op.f("ck_data_quality_issues_period_in_order")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "import_id"],
            ["data_imports.organization_id", "data_imports.id"],
            name=op.f("fk_data_quality_issues_organization_id_data_imports"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_data_quality_issues_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_quality_issues")),
    )
    op.create_index(
        "ix_data_quality_issues_org_open",
        "data_quality_issues",
        ["organization_id", "resolved_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_data_quality_issues_organization_id"),
        "data_quality_issues",
        ["organization_id"],
        unique=False,
    )
    op.add_column("customers", sa.Column("import_id", sa.Uuid(), nullable=True))
    op.create_index(
        "ix_customers_org_import", "customers", ["organization_id", "import_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_customers_organization_id_data_imports"),
        "customers",
        "data_imports",
        ["organization_id", "import_id"],
        ["organization_id", "id"],
    )
    op.add_column("expenses", sa.Column("import_id", sa.Uuid(), nullable=True))
    op.create_index(
        "ix_expenses_org_import", "expenses", ["organization_id", "import_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_expenses_organization_id_data_imports"),
        "expenses",
        "data_imports",
        ["organization_id", "import_id"],
        ["organization_id", "id"],
    )
    op.add_column("products", sa.Column("import_id", sa.Uuid(), nullable=True))
    op.create_index(
        "ix_products_org_import", "products", ["organization_id", "import_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_products_organization_id_data_imports"),
        "products",
        "data_imports",
        ["organization_id", "import_id"],
        ["organization_id", "id"],
    )
    op.add_column("sales", sa.Column("import_id", sa.Uuid(), nullable=True))
    op.create_index("ix_sales_org_import", "sales", ["organization_id", "import_id"], unique=False)
    op.create_foreign_key(
        op.f("fk_sales_organization_id_data_imports"),
        "sales",
        "data_imports",
        ["organization_id", "import_id"],
        ["organization_id", "id"],
    )
    op.add_column("stock_movements", sa.Column("import_id", sa.Uuid(), nullable=True))
    op.create_index(
        "ix_stock_movements_org_import",
        "stock_movements",
        ["organization_id", "import_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_stock_movements_organization_id_data_imports"),
        "stock_movements",
        "data_imports",
        ["organization_id", "import_id"],
        ["organization_id", "id"],
    )
    op.add_column("suppliers", sa.Column("import_id", sa.Uuid(), nullable=True))
    op.create_index(
        "ix_suppliers_org_import", "suppliers", ["organization_id", "import_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_suppliers_organization_id_data_imports"),
        "suppliers",
        "data_imports",
        ["organization_id", "import_id"],
        ["organization_id", "id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_suppliers_organization_id_data_imports"), "suppliers", type_="foreignkey"
    )
    op.drop_index("ix_suppliers_org_import", table_name="suppliers")
    op.drop_column("suppliers", "import_id")
    op.drop_constraint(
        op.f("fk_stock_movements_organization_id_data_imports"),
        "stock_movements",
        type_="foreignkey",
    )
    op.drop_index("ix_stock_movements_org_import", table_name="stock_movements")
    op.drop_column("stock_movements", "import_id")
    op.drop_constraint(op.f("fk_sales_organization_id_data_imports"), "sales", type_="foreignkey")
    op.drop_index("ix_sales_org_import", table_name="sales")
    op.drop_column("sales", "import_id")
    op.drop_constraint(
        op.f("fk_products_organization_id_data_imports"), "products", type_="foreignkey"
    )
    op.drop_index("ix_products_org_import", table_name="products")
    op.drop_column("products", "import_id")
    op.drop_constraint(
        op.f("fk_expenses_organization_id_data_imports"), "expenses", type_="foreignkey"
    )
    op.drop_index("ix_expenses_org_import", table_name="expenses")
    op.drop_column("expenses", "import_id")
    op.drop_constraint(
        op.f("fk_customers_organization_id_data_imports"), "customers", type_="foreignkey"
    )
    op.drop_index("ix_customers_org_import", table_name="customers")
    op.drop_column("customers", "import_id")
    op.drop_index(op.f("ix_data_quality_issues_organization_id"), table_name="data_quality_issues")
    op.drop_index("ix_data_quality_issues_org_open", table_name="data_quality_issues")
    op.drop_table("data_quality_issues")
    op.drop_index(op.f("ix_data_import_rows_organization_id"), table_name="data_import_rows")
    op.drop_index("ix_data_import_rows_import_status", table_name="data_import_rows")
    op.drop_table("data_import_rows")
    op.drop_index(op.f("ix_data_imports_organization_id"), table_name="data_imports")
    op.drop_index("ix_data_imports_org_sha256", table_name="data_imports")
    op.drop_index("ix_data_imports_org_created", table_name="data_imports")
    op.drop_table("data_imports")
    op.drop_index(op.f("ix_data_sources_organization_id"), table_name="data_sources")
    op.drop_table("data_sources")
    # ### end Alembic commands ###
