"""business health tables

Revision ID: 43f0669aba3e
Revises: e5b2a817c4f6
Create Date: 2026-10-02 22:08:19.107331
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "43f0669aba3e"
down_revision: str | None = "e5b2a817c4f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "health_category_weights",
        sa.Column("category", sa.String(length=15), nullable=False),
        sa.Column("weight", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("industry_code", sa.String(length=50), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('financial', 'sales', 'customer', 'marketing', 'inventory', 'operational')",
            name=op.f("ck_health_category_weights_category_valid"),
        ),
        sa.CheckConstraint(
            "weight >= 0", name=op.f("ck_health_category_weights_weight_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["industry_code"],
            ["industries.code"],
            name=op.f("fk_health_category_weights_industry_code_industries"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_category_weights")),
    )
    op.create_index(
        "uq_health_category_weights_general",
        "health_category_weights",
        ["category"],
        unique=True,
        postgresql_where=sa.text("industry_code IS NULL"),
    )
    op.create_index(
        "uq_health_category_weights_industry",
        "health_category_weights",
        ["category", "industry_code"],
        unique=True,
        postgresql_where=sa.text("industry_code IS NOT NULL"),
    )
    op.create_table(
        "business_health",
        sa.Column("granularity", sa.String(length=10), server_default="month", nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("is_complete", sa.Boolean(), nullable=False),
        sa.Column("overall_score", sa.SmallInteger(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("previous_score", sa.SmallInteger(), nullable=True),
        sa.Column("trend", sa.String(length=5), nullable=True),
        sa.Column("coverage_pct", sa.SmallInteger(), nullable=False),
        sa.Column("data_quality", sa.SmallInteger(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(overall_score IS NULL) = (status = 'not_enough_data')",
            name=op.f("ck_business_health_score_matches_status"),
        ),
        sa.CheckConstraint(
            "granularity = 'month'", name=op.f("ck_business_health_granularity_valid")
        ),
        sa.CheckConstraint(
            "status IN ('healthy', 'fair', 'needs_attention', 'at_risk', 'not_enough_data')",
            name=op.f("ck_business_health_status_valid"),
        ),
        sa.CheckConstraint(
            "trend IN ('up', 'down', 'flat')", name=op.f("ck_business_health_trend_valid")
        ),
        sa.CheckConstraint(
            "coverage_pct BETWEEN 0 AND 100", name=op.f("ck_business_health_coverage_in_range")
        ),
        sa.CheckConstraint(
            "overall_score IS NULL OR overall_score BETWEEN 0 AND 100",
            name=op.f("ck_business_health_score_in_range"),
        ),
        sa.CheckConstraint(
            "period_end >= period_start", name=op.f("ck_business_health_period_in_order")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_business_health_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_health")),
        sa.UniqueConstraint(
            "organization_id", "granularity", "period_start", name="uq_business_health_period"
        ),
        sa.UniqueConstraint("organization_id", "id", name="uq_business_health_org_id"),
    )
    op.create_index(
        "ix_business_health_org_period",
        "business_health",
        ["organization_id", "period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_business_health_organization_id"),
        "business_health",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "health_rules",
        sa.Column("category", sa.String(length=15), nullable=False),
        sa.Column("kpi_code", sa.String(length=60), nullable=False),
        sa.Column("basis", sa.String(length=12), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("threshold_bad", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("threshold_ok", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("threshold_good", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("weight", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("industry_code", sa.String(length=50), nullable=True),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(direction = 'up_good' AND threshold_bad < threshold_ok AND threshold_ok < threshold_good) OR (direction = 'down_good' AND threshold_bad > threshold_ok AND threshold_ok > threshold_good)",
            name=op.f("ck_health_rules_thresholds_in_order"),
        ),
        sa.CheckConstraint(
            "basis IN ('value', 'vs_baseline')", name=op.f("ck_health_rules_basis_valid")
        ),
        sa.CheckConstraint(
            "category IN ('financial', 'sales', 'customer', 'marketing', 'inventory', 'operational')",
            name=op.f("ck_health_rules_category_valid"),
        ),
        sa.CheckConstraint(
            "direction IN ('up_good', 'down_good')", name=op.f("ck_health_rules_direction_valid")
        ),
        sa.CheckConstraint("weight > 0", name=op.f("ck_health_rules_weight_positive")),
        sa.ForeignKeyConstraint(
            ["industry_code"],
            ["industries.code"],
            name=op.f("fk_health_rules_industry_code_industries"),
        ),
        sa.ForeignKeyConstraint(
            ["kpi_code"],
            ["kpi_definitions.code"],
            name=op.f("fk_health_rules_kpi_code_kpi_definitions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_health_rules")),
    )
    op.create_index(
        "uq_health_rules_general",
        "health_rules",
        ["kpi_code"],
        unique=True,
        postgresql_where=sa.text("industry_code IS NULL"),
    )
    op.create_index(
        "uq_health_rules_industry",
        "health_rules",
        ["kpi_code", "industry_code"],
        unique=True,
        postgresql_where=sa.text("industry_code IS NOT NULL"),
    )
    op.create_table(
        "business_health_components",
        sa.Column("health_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=15), nullable=False),
        sa.Column("score", sa.SmallInteger(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("previous_score", sa.SmallInteger(), nullable=True),
        sa.Column("trend", sa.String(length=5), nullable=True),
        sa.Column("weight", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("contribution", sa.Numeric(precision=7, scale=2), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(score IS NULL) = (status = 'not_enough_data')",
            name=op.f("ck_business_health_components_score_matches_status"),
        ),
        sa.CheckConstraint(
            "category IN ('financial', 'sales', 'customer', 'marketing', 'inventory', 'operational')",
            name=op.f("ck_business_health_components_category_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('healthy', 'fair', 'needs_attention', 'at_risk', 'not_enough_data')",
            name=op.f("ck_business_health_components_status_valid"),
        ),
        sa.CheckConstraint(
            "trend IN ('up', 'down', 'flat')",
            name=op.f("ck_business_health_components_trend_valid"),
        ),
        sa.CheckConstraint(
            "score IS NULL OR score BETWEEN 0 AND 100",
            name=op.f("ck_business_health_components_score_in_range"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "health_id"],
            ["business_health.organization_id", "business_health.id"],
            name=op.f("fk_business_health_components_organization_id_business_health"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_business_health_components_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_health_components")),
        sa.UniqueConstraint("health_id", "category", name="uq_business_health_components_category"),
    )
    op.create_index(
        "ix_business_health_components_health",
        "business_health_components",
        ["health_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_business_health_components_organization_id"),
        "business_health_components",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_business_health_components_organization_id"),
        table_name="business_health_components",
    )
    op.drop_index("ix_business_health_components_health", table_name="business_health_components")
    op.drop_table("business_health_components")
    op.drop_index(
        "uq_health_rules_industry",
        table_name="health_rules",
        postgresql_where=sa.text("industry_code IS NOT NULL"),
    )
    op.drop_index(
        "uq_health_rules_general",
        table_name="health_rules",
        postgresql_where=sa.text("industry_code IS NULL"),
    )
    op.drop_table("health_rules")
    op.drop_index(op.f("ix_business_health_organization_id"), table_name="business_health")
    op.drop_index("ix_business_health_org_period", table_name="business_health")
    op.drop_table("business_health")
    op.drop_index(
        "uq_health_category_weights_industry",
        table_name="health_category_weights",
        postgresql_where=sa.text("industry_code IS NOT NULL"),
    )
    op.drop_index(
        "uq_health_category_weights_general",
        table_name="health_category_weights",
        postgresql_where=sa.text("industry_code IS NULL"),
    )
    op.drop_table("health_category_weights")
    # ### end Alembic commands ###
