"""notification preferences

Revision ID: 296030419acc
Revises: 8458ef156a00
Create Date: 2026-09-26 11:56:28.393722
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "296030419acc"
down_revision: str | None = "8458ef156a00"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_preferences",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("email", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("in_app", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("push", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category <> 'security' OR (email AND in_app)",
            name=op.f("ck_notification_preferences_security_always_delivered"),
        ),
        sa.CheckConstraint(
            "category IN ('sales', 'financial', 'customer', 'inventory', 'marketing', 'forecast', 'action', 'data', 'security')",
            name=op.f("ck_notification_preferences_category_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_notification_preferences_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notification_preferences_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notification_preferences")),
        sa.UniqueConstraint(
            "organization_id",
            "user_id",
            "category",
            name=op.f("uq_notification_preferences_organization_id_user_id_category"),
        ),
    )
    op.create_index(
        op.f("ix_notification_preferences_organization_id"),
        "notification_preferences",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_preferences_user_id"),
        "notification_preferences",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_notification_preferences_user_id"), table_name="notification_preferences"
    )
    op.drop_index(
        op.f("ix_notification_preferences_organization_id"), table_name="notification_preferences"
    )
    op.drop_table("notification_preferences")
    # ### end Alembic commands ###
