"""business profile, settings, goals, seasons, benchmarks

Revision ID: 97b99f43f225
Revises: cee5c110fba7
Create Date: 2026-09-26 10:50:43.402133
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "97b99f43f225"
down_revision: str | None = "cee5c110fba7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Frozen seed (decision 2026-09-26): a short Vyterlix industry list. UK SIC 2007 codes are
# stored separately on each profile for precision. Later changes get their own migration.
INDUSTRIES = [
    ("retail", "Retail (shops)"),
    ("ecommerce", "E-commerce / online store"),
    ("hospitality", "Hospitality (restaurants, cafés, bars, hotels)"),
    ("health_beauty", "Health & beauty (salons, clinics, gyms)"),
    ("professional_services", "Professional services (legal, accounting, consulting)"),
    ("construction_trades", "Construction & trades"),
    ("manufacturing", "Manufacturing"),
    ("wholesale_distribution", "Wholesale & distribution"),
    ("logistics_transport", "Logistics & transport"),
    ("technology", "Technology & software"),
    ("creative_media", "Creative & media"),
    ("education_training", "Education & training"),
    ("agriculture_food", "Agriculture & food production"),
    ("other", "Other"),
]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "industries",
        sa.Column("code", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.PrimaryKeyConstraint("code", name=op.f("pk_industries")),
    )
    op.create_table(
        "business_benchmarks",
        sa.Column("industry_code", sa.String(length=50), nullable=False),
        sa.Column("sic_code", sa.String(length=5), nullable=True),
        sa.Column("region", sa.String(length=40), nullable=True),
        sa.Column("size_band", sa.String(length=10), nullable=True),
        sa.Column("kpi_code", sa.String(length=100), nullable=False),
        sa.Column("period_year", sa.SmallInteger(), nullable=False),
        sa.Column("value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("source_url", sa.String(length=500), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "region IN ('north_east', 'north_west', 'yorkshire_and_the_humber', 'east_midlands', 'west_midlands', 'east_of_england', 'london', 'south_east', 'south_west', 'wales', 'scotland', 'northern_ireland')",
            name=op.f("ck_business_benchmarks_region_valid"),
        ),
        sa.CheckConstraint(
            "sic_code ~ '^[0-9]{5}$'", name=op.f("ck_business_benchmarks_sic_code_format")
        ),
        sa.CheckConstraint(
            "size_band IN ('micro', 'small', 'medium', 'large')",
            name=op.f("ck_business_benchmarks_size_band_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["industry_code"],
            ["industries.code"],
            name=op.f("fk_business_benchmarks_industry_code_industries"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_benchmarks")),
    )
    op.create_index(
        "uq_business_benchmarks_segment",
        "business_benchmarks",
        ["industry_code", "sic_code", "region", "size_band", "kpi_code", "period_year"],
        unique=True,
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "business_goals",
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("goal_type", sa.String(length=40), nullable=False),
        sa.Column("kpi_code", sa.String(length=100), nullable=True),
        sa.Column("baseline_value", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("target_value", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("target_unit", sa.String(length=10), nullable=True),
        sa.Column("target_date", sa.Date(), nullable=True),
        sa.Column("priority", sa.SmallInteger(), server_default=sa.text("3"), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="active", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "goal_type IN ('increase_revenue', 'improve_margin', 'reduce_costs', 'grow_customers', 'improve_retention', 'improve_cash_flow', 'reduce_stock_problems', 'other')",
            name=op.f("ck_business_goals_goal_type_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('active', 'achieved', 'abandoned')",
            name=op.f("ck_business_goals_status_valid"),
        ),
        sa.CheckConstraint(
            "target_unit IN ('gbp', 'percent', 'count')",
            name=op.f("ck_business_goals_target_unit_valid"),
        ),
        sa.CheckConstraint(
            "(target_value IS NULL) = (target_unit IS NULL)",
            name=op.f("ck_business_goals_target_value_has_unit"),
        ),
        sa.CheckConstraint(
            "priority BETWEEN 1 AND 5", name=op.f("ck_business_goals_priority_range")
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_business_goals_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_business_goals_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_goals")),
    )
    op.create_index(
        op.f("ix_business_goals_organization_id"),
        "business_goals",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "business_profiles",
        sa.Column("industry_code", sa.String(length=50), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="GBP", nullable=False),
        sa.Column("fiscal_year_start_month", sa.SmallInteger(), nullable=False),
        sa.Column("fiscal_year_start_day", sa.SmallInteger(), nullable=False),
        sa.Column("sic_code", sa.String(length=5), nullable=True),
        sa.Column("country", sa.String(length=2), server_default="GB", nullable=False),
        sa.Column("region", sa.String(length=40), nullable=True),
        sa.Column("town_city", sa.String(length=100), nullable=True),
        sa.Column("postcode", sa.String(length=8), nullable=True),
        sa.Column("business_size", sa.String(length=10), nullable=True),
        sa.Column("business_model", sa.String(length=20), nullable=True),
        sa.Column("team_size", sa.Integer(), nullable=True),
        sa.Column("founded_year", sa.SmallInteger(), nullable=True),
        sa.Column("vat_registered", sa.Boolean(), nullable=True),
        sa.Column("vat_number", sa.String(length=14), nullable=True),
        sa.Column("onboarding_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "business_model IN ('b2c', 'b2b', 'b2b_and_b2c', 'marketplace', 'subscription')",
            name=op.f("ck_business_profiles_business_model_valid"),
        ),
        sa.CheckConstraint(
            "business_size IN ('micro', 'small', 'medium', 'large')",
            name=op.f("ck_business_profiles_business_size_valid"),
        ),
        sa.CheckConstraint("country = 'GB'", name=op.f("ck_business_profiles_country_gb")),
        sa.CheckConstraint("currency = 'GBP'", name=op.f("ck_business_profiles_currency_gbp")),
        sa.CheckConstraint(
            "postcode ~ '^([A-Z]{1,2}[0-9][A-Z0-9]? [0-9][A-Z]{2}|GIR 0AA)$'",
            name=op.f("ck_business_profiles_postcode_format"),
        ),
        sa.CheckConstraint(
            "region IN ('north_east', 'north_west', 'yorkshire_and_the_humber', 'east_midlands', 'west_midlands', 'east_of_england', 'london', 'south_east', 'south_west', 'wales', 'scotland', 'northern_ireland')",
            name=op.f("ck_business_profiles_region_valid"),
        ),
        sa.CheckConstraint(
            "sic_code ~ '^[0-9]{5}$'", name=op.f("ck_business_profiles_sic_code_format")
        ),
        sa.CheckConstraint(
            "vat_number ~ '^GB([0-9]{9}|[0-9]{12})$'",
            name=op.f("ck_business_profiles_vat_number_format"),
        ),
        sa.CheckConstraint(
            "fiscal_year_start_month BETWEEN 1 AND 12 AND fiscal_year_start_day >= 1 AND fiscal_year_start_day <= CASE WHEN fiscal_year_start_month = 2 THEN 28 WHEN fiscal_year_start_month IN (4, 6, 9, 11) THEN 30 ELSE 31 END",
            name=op.f("ck_business_profiles_fiscal_year_start_valid"),
        ),
        sa.CheckConstraint(
            "founded_year BETWEEN 1800 AND 2100",
            name=op.f("ck_business_profiles_founded_year_range"),
        ),
        sa.CheckConstraint(
            "team_size >= 0", name=op.f("ck_business_profiles_team_size_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["industry_code"],
            ["industries.code"],
            name=op.f("fk_business_profiles_industry_code_industries"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_business_profiles_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_profiles")),
        sa.UniqueConstraint("organization_id", name=op.f("uq_business_profiles_organization_id")),
    )
    op.create_index(
        op.f("ix_business_profiles_organization_id"),
        "business_profiles",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "business_seasons",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("start_month", sa.SmallInteger(), nullable=False),
        sa.Column("start_day", sa.SmallInteger(), nullable=False),
        sa.Column("end_month", sa.SmallInteger(), nullable=False),
        sa.Column("end_day", sa.SmallInteger(), nullable=False),
        sa.Column("expected_change_pct", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("source", sa.String(length=10), server_default="user", nullable=False),
        sa.Column("status", sa.String(length=10), server_default="active", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source = 'detected' OR status <> 'suggested'",
            name=op.f("ck_business_seasons_only_detected_are_suggested"),
        ),
        sa.CheckConstraint(
            "source IN ('user', 'detected')", name=op.f("ck_business_seasons_source_valid")
        ),
        sa.CheckConstraint(
            "status IN ('active', 'suggested', 'dismissed')",
            name=op.f("ck_business_seasons_status_valid"),
        ),
        sa.CheckConstraint(
            "end_month BETWEEN 1 AND 12 AND end_day >= 1 AND end_day <= CASE WHEN end_month = 2 THEN 28 WHEN end_month IN (4, 6, 9, 11) THEN 30 ELSE 31 END",
            name=op.f("ck_business_seasons_end_valid"),
        ),
        sa.CheckConstraint(
            "expected_change_pct BETWEEN -100 AND 1000",
            name=op.f("ck_business_seasons_expected_change_pct_range"),
        ),
        sa.CheckConstraint(
            "start_month BETWEEN 1 AND 12 AND start_day >= 1 AND start_day <= CASE WHEN start_month = 2 THEN 28 WHEN start_month IN (4, 6, 9, 11) THEN 30 ELSE 31 END",
            name=op.f("ck_business_seasons_start_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_business_seasons_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_seasons")),
    )
    op.create_index(
        op.f("ix_business_seasons_organization_id"),
        "business_seasons",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "business_settings",
        sa.Column("timezone", sa.String(length=64), server_default="Europe/London", nullable=False),
        sa.Column("locale", sa.String(length=10), server_default="en-GB", nullable=False),
        sa.Column("week_start_day", sa.SmallInteger(), server_default=sa.text("1"), nullable=False),
        sa.Column("quiet_hours_start", sa.Time(), nullable=True),
        sa.Column("quiet_hours_end", sa.Time(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("locale = 'en-GB'", name=op.f("ck_business_settings_locale_en_gb")),
        sa.CheckConstraint(
            "timezone = 'Europe/London'", name=op.f("ck_business_settings_timezone_uk")
        ),
        sa.CheckConstraint(
            "(quiet_hours_start IS NULL) = (quiet_hours_end IS NULL)",
            name=op.f("ck_business_settings_quiet_hours_pair"),
        ),
        sa.CheckConstraint(
            "week_start_day BETWEEN 1 AND 7", name=op.f("ck_business_settings_week_start_day_valid")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_business_settings_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_business_settings")),
        sa.UniqueConstraint("organization_id", name=op.f("uq_business_settings_organization_id")),
    )
    op.create_index(
        op.f("ix_business_settings_organization_id"),
        "business_settings",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###
    op.bulk_insert(
        sa.table(
            "industries",
            sa.column("code"),
            sa.column("label"),
            sa.column("sort_order", sa.SmallInteger),
        ),
        [
            {"code": code, "label": label, "sort_order": i}
            for i, (code, label) in enumerate(INDUSTRIES, start=1)
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_business_settings_organization_id"), table_name="business_settings")
    op.drop_table("business_settings")
    op.drop_index(op.f("ix_business_seasons_organization_id"), table_name="business_seasons")
    op.drop_table("business_seasons")
    op.drop_index(op.f("ix_business_profiles_organization_id"), table_name="business_profiles")
    op.drop_table("business_profiles")
    op.drop_index(op.f("ix_business_goals_organization_id"), table_name="business_goals")
    op.drop_table("business_goals")
    op.drop_index(
        "uq_business_benchmarks_segment",
        table_name="business_benchmarks",
        postgresql_nulls_not_distinct=True,
    )
    op.drop_table("business_benchmarks")
    op.drop_table("industries")
    # ### end Alembic commands ###
