"""outcome tables

Revision ID: b699b158365f
Revises: 86f3a18e04cb
Create Date: 2026-10-05 11:03:15.578139
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b699b158365f"
down_revision: str | None = "86f3a18e04cb"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "follow_up_schedules",
        sa.Column("intervention_id", sa.Uuid(), nullable=False),
        sa.Column("action_id", sa.Uuid(), nullable=True),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("measure_month", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=10), server_default="scheduled", nullable=False),
        sa.Column("responsible_user_id", sa.Uuid(), nullable=True),
        sa.Column("notified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('scheduled', 'done')", name=op.f("ck_follow_up_schedules_status_valid")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "intervention_id"],
            ["interventions.organization_id", "interventions.id"],
            name=op.f("fk_follow_up_schedules_organization_id_interventions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_follow_up_schedules_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["responsible_user_id"],
            ["users.id"],
            name=op.f("fk_follow_up_schedules_responsible_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_follow_up_schedules")),
        sa.UniqueConstraint("intervention_id", name="uq_follow_up_schedules_intervention"),
    )
    op.create_index(
        "ix_follow_up_schedules_due",
        "follow_up_schedules",
        ["organization_id", "status", "due_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_follow_up_schedules_organization_id"),
        "follow_up_schedules",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "intervention_outcomes",
        sa.Column("intervention_id", sa.Uuid(), nullable=False),
        sa.Column("outcome", sa.String(length=25), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("baseline_period", sa.Date(), nullable=True),
        sa.Column("baseline_value", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("measured_period", sa.Date(), nullable=True),
        sa.Column("measured_value", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("expected_change", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("actual_change", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("seasonal_change", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("adjusted_change", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("achieved_pct", sa.SmallInteger(), nullable=True),
        sa.Column("data_quality", sa.SmallInteger(), nullable=True),
        sa.Column("rules_version", sa.String(length=30), nullable=False),
        sa.Column(
            "details",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("measured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("measured_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "outcome IN ('successful', 'partially_successful', 'unsuccessful', 'inconclusive')",
            name=op.f("ck_intervention_outcomes_outcome_valid"),
        ),
        sa.CheckConstraint(
            "data_quality IS NULL OR data_quality BETWEEN 0 AND 100",
            name=op.f("ck_intervention_outcomes_quality_in_range"),
        ),
        sa.ForeignKeyConstraint(
            ["measured_by_user_id"],
            ["users.id"],
            name=op.f("fk_intervention_outcomes_measured_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "intervention_id"],
            ["interventions.organization_id", "interventions.id"],
            name=op.f("fk_intervention_outcomes_organization_id_interventions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_intervention_outcomes_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intervention_outcomes")),
        sa.UniqueConstraint("intervention_id", name="uq_intervention_outcomes_intervention"),
    )
    op.create_index(
        "ix_intervention_outcomes_org",
        "intervention_outcomes",
        ["organization_id", "measured_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_intervention_outcomes_organization_id"),
        "intervention_outcomes",
        ["organization_id"],
        unique=False,
    )
    # The history of an action can now record that its result was measured.
    op.drop_constraint(op.f("ck_action_updates_kind_valid"), "action_updates", type_="check")
    op.create_check_constraint(
        op.f("ck_action_updates_kind_valid"),
        "action_updates",
        "kind IN ('created', 'approved', 'rejected', 'status', 'note', 'assignment', 'dates', 'modification', 'steps', 'evidence', 'overdue', 'outcome')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_constraint(op.f("ck_action_updates_kind_valid"), "action_updates", type_="check")
    op.create_check_constraint(
        op.f("ck_action_updates_kind_valid"),
        "action_updates",
        "kind IN ('created', 'approved', 'rejected', 'status', 'note', 'assignment', 'dates', 'modification', 'steps', 'evidence', 'overdue')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_intervention_outcomes_organization_id"), table_name="intervention_outcomes"
    )
    op.drop_index("ix_intervention_outcomes_org", table_name="intervention_outcomes")
    op.drop_table("intervention_outcomes")
    op.drop_index(op.f("ix_follow_up_schedules_organization_id"), table_name="follow_up_schedules")
    op.drop_index("ix_follow_up_schedules_due", table_name="follow_up_schedules")
    op.drop_table("follow_up_schedules")
    # ### end Alembic commands ###
