"""business memory tables

Revision ID: 27af5a64e938
Revises: b699b158365f
Create Date: 2026-10-05 13:01:25.651275
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '27af5a64e938'
down_revision: str | None = 'b699b158365f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_memory',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('source', sa.String(length=10), nullable=False),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('normal_range', 'customer_pattern', 'goal', 'season', 'constraint', 'preference')", name=op.f('ck_business_memory_kind_valid')),
    sa.CheckConstraint("source IN ('derived', 'owner')", name=op.f('ck_business_memory_source_valid')),
    sa.CheckConstraint('length(trim(key)) > 0', name=op.f('ck_business_memory_key_not_blank')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_business_memory_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_business_memory_updated_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_memory')),
    sa.UniqueConstraint('organization_id', 'kind', 'key', name='uq_business_memory_key')
    )
    op.create_index(op.f('ix_business_memory_organization_id'), 'business_memory', ['organization_id'], unique=False)
    op.create_table('intervention_patterns',
    sa.Column('library_code', sa.String(length=60), nullable=False),
    sa.Column('kpi_code', sa.String(length=60), nullable=False),
    sa.Column('successful', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('partially_successful', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('unsuccessful', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('inconclusive', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('average_achieved_pct', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('last_outcome', sa.String(length=25), nullable=True),
    sa.Column('last_measured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('successful >= 0 AND partially_successful >= 0 AND unsuccessful >= 0 AND inconclusive >= 0', name=op.f('ck_intervention_patterns_counts_not_negative')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_intervention_patterns_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intervention_patterns')),
    sa.UniqueConstraint('organization_id', 'library_code', 'kpi_code', name='uq_intervention_patterns_key')
    )
    op.create_index(op.f('ix_intervention_patterns_organization_id'), 'intervention_patterns', ['organization_id'], unique=False)
    op.create_table('memory_retrieval_events',
    sa.Column('purpose', sa.String(length=30), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('used', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_memory_retrieval_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_memory_retrieval_events'))
    )
    op.create_index(op.f('ix_memory_retrieval_events_organization_id'), 'memory_retrieval_events', ['organization_id'], unique=False)
    op.create_index('ix_memory_retrieval_org', 'memory_retrieval_events', ['organization_id', 'created_at'], unique=False)
    op.create_table('business_learning',
    sa.Column('intervention_id', sa.Uuid(), nullable=False),
    sa.Column('library_code', sa.String(length=60), nullable=True),
    sa.Column('kpi_code', sa.String(length=60), nullable=False),
    sa.Column('outcome', sa.String(length=25), nullable=False),
    sa.Column('achieved_pct', sa.SmallInteger(), nullable=True),
    sa.Column('lesson', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("outcome IN ('successful', 'partially_successful', 'unsuccessful', 'inconclusive')", name=op.f('ck_business_learning_outcome_valid')),
    sa.ForeignKeyConstraint(['organization_id', 'intervention_id'], ['interventions.organization_id', 'interventions.id'], name=op.f('fk_business_learning_organization_id_interventions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_business_learning_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_learning')),
    sa.UniqueConstraint('intervention_id', name='uq_business_learning_intervention')
    )
    op.create_index('ix_business_learning_org_kpi', 'business_learning', ['organization_id', 'kpi_code'], unique=False)
    op.create_index(op.f('ix_business_learning_organization_id'), 'business_learning', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_learning_organization_id'), table_name='business_learning')
    op.drop_index('ix_business_learning_org_kpi', table_name='business_learning')
    op.drop_table('business_learning')
    op.drop_index('ix_memory_retrieval_org', table_name='memory_retrieval_events')
    op.drop_index(op.f('ix_memory_retrieval_events_organization_id'), table_name='memory_retrieval_events')
    op.drop_table('memory_retrieval_events')
    op.drop_index(op.f('ix_intervention_patterns_organization_id'), table_name='intervention_patterns')
    op.drop_table('intervention_patterns')
    op.drop_index(op.f('ix_business_memory_organization_id'), table_name='business_memory')
    op.drop_table('business_memory')
    # ### end Alembic commands ###
