"""onboarding skipped sections

Revision ID: acb5c30bed41
Revises: b5e9fe449f53
Create Date: 2026-09-26 12:29:10.522453
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "acb5c30bed41"
down_revision: str | None = "b5e9fe449f53"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "business_profiles",
        sa.Column(
            "onboarding_skipped",
            postgresql.ARRAY(sa.String(length=30)),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("business_profiles", "onboarding_skipped")
    # ### end Alembic commands ###
