"""admin flags cases notes events

Revision ID: 7f55338ae22a
Revises: 263283b7b7e9
Create Date: 2026-10-10 08:33:34.918458
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "7f55338ae22a"
down_revision: str | None = "263283b7b7e9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_flags",
        sa.Column("key", sa.String(length=41), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "org_overrides",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "key ~ '^[a-z][a-z0-9_]{2,40}$'", name=op.f("ck_feature_flags_key_format")
        ),
        sa.CheckConstraint(
            "length(trim(description)) > 0", name=op.f("ck_feature_flags_description_not_blank")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_flags")),
        sa.UniqueConstraint("key", name=op.f("uq_feature_flags_key")),
    )
    op.create_table(
        "support_cases",
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("requester_email", sa.String(length=320), nullable=True),
        sa.Column("subject", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=10), server_default="open", nullable=False),
        sa.Column("priority", sa.String(length=10), server_default="normal", nullable=False),
        sa.Column("assigned_to_user_id", sa.Uuid(), nullable=True),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'resolved') = (resolved_at IS NOT NULL)",
            name=op.f("ck_support_cases_resolved_has_a_time"),
        ),
        sa.CheckConstraint(
            "priority IN ('low', 'normal', 'high')", name=op.f("ck_support_cases_priority_valid")
        ),
        sa.CheckConstraint(
            "status IN ('open', 'waiting', 'resolved')", name=op.f("ck_support_cases_status_valid")
        ),
        sa.CheckConstraint(
            "length(trim(subject)) > 0", name=op.f("ck_support_cases_subject_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["assigned_to_user_id"],
            ["users.id"],
            name=op.f("fk_support_cases_assigned_to_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_support_cases_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_support_cases_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_support_cases")),
    )
    op.create_index(
        op.f("ix_support_cases_organization_id"), "support_cases", ["organization_id"], unique=False
    )
    op.create_index(
        "ix_support_cases_status", "support_cases", ["status", "created_at"], unique=False
    )
    op.create_table(
        "system_events",
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("message", sa.String(length=300), nullable=False),
        sa.Column(
            "details", postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True
        ),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "severity IN ('info', 'warning', 'error')", name=op.f("ck_system_events_severity_valid")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_system_events_organization_id_organizations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["users.id"],
            name=op.f("fk_system_events_resolved_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_events")),
    )
    op.create_index("ix_system_events_created", "system_events", ["created_at"], unique=False)
    op.create_index(
        "ix_system_events_open", "system_events", ["severity", "created_at"], unique=False
    )
    op.create_table(
        "admin_notes",
        sa.Column("case_id", sa.Uuid(), nullable=True),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("author_user_id", sa.Uuid(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("clock_timestamp()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "case_id IS NOT NULL OR organization_id IS NOT NULL OR user_id IS NOT NULL",
            name=op.f("ck_admin_notes_has_a_subject"),
        ),
        sa.CheckConstraint("length(trim(body)) > 0", name=op.f("ck_admin_notes_body_not_blank")),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.id"],
            name=op.f("fk_admin_notes_author_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["case_id"],
            ["support_cases.id"],
            name=op.f("fk_admin_notes_case_id_support_cases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_admin_notes_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_admin_notes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_admin_notes")),
    )
    op.create_index("ix_admin_notes_case", "admin_notes", ["case_id", "created_at"], unique=False)
    op.create_index(
        "ix_admin_notes_org", "admin_notes", ["organization_id", "created_at"], unique=False
    )
    op.create_index("ix_admin_notes_user", "admin_notes", ["user_id", "created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_admin_notes_user", table_name="admin_notes")
    op.drop_index("ix_admin_notes_org", table_name="admin_notes")
    op.drop_index("ix_admin_notes_case", table_name="admin_notes")
    op.drop_table("admin_notes")
    op.drop_index("ix_system_events_open", table_name="system_events")
    op.drop_index("ix_system_events_created", table_name="system_events")
    op.drop_table("system_events")
    op.drop_index("ix_support_cases_status", table_name="support_cases")
    op.drop_index(op.f("ix_support_cases_organization_id"), table_name="support_cases")
    op.drop_table("support_cases")
    op.drop_table("feature_flags")
    # ### end Alembic commands ###
