"""integrations

Revision ID: a27cdf228a45
Revises: a4c1e7d09b52
Create Date: 2026-10-02 19:11:07.897352
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a27cdf228a45"
down_revision: str | None = "a4c1e7d09b52"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integration_oauth_states",
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("integration_id", sa.Uuid(), nullable=True),
        sa.Column("state_hash", sa.String(length=64), nullable=False),
        sa.Column("code_verifier", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "provider ~ '^[a-z][a-z_]*$'", name=op.f("ck_integration_oauth_states_provider_format")
        ),
        sa.CheckConstraint(
            "state_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_integration_oauth_states_state_hash_format"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_integration_oauth_states_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_integration_oauth_states_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_oauth_states")),
        sa.UniqueConstraint("state_hash", name="uq_integration_oauth_states_hash"),
    )
    op.create_index(
        "ix_integration_oauth_states_expires",
        "integration_oauth_states",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_oauth_states_organization_id"),
        "integration_oauth_states",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "integrations",
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=15), server_default="connected", nullable=False),
        sa.Column("display_name", sa.String(length=150), nullable=False),
        sa.Column("external_account_id", sa.String(length=200), nullable=False),
        sa.Column("external_account_name", sa.String(length=200), nullable=True),
        sa.Column(
            "granted_scopes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "settings",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("credentials", sa.Text(), nullable=True),
        sa.Column("token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("connected_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("connected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("disconnected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_successful_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_sync_status", sa.String(length=10), nullable=True),
        sa.Column("last_error_code", sa.String(length=60), nullable=True),
        sa.Column("last_error_message", sa.String(length=500), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "consecutive_failures", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "sync_cursor",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "last_sync_status IS NULL OR last_sync_status IN ('succeeded', 'failed')",
            name=op.f("ck_integrations_last_sync_status_valid"),
        ),
        sa.CheckConstraint(
            "provider ~ '^[a-z][a-z_]*$'", name=op.f("ck_integrations_provider_format")
        ),
        sa.CheckConstraint(
            "status <> 'disconnected' OR (credentials IS NULL AND disconnected_at IS NOT NULL)",
            name=op.f("ck_integrations_disconnected_has_no_credentials"),
        ),
        sa.CheckConstraint(
            "status = 'disconnected' OR credentials IS NOT NULL",
            name=op.f("ck_integrations_connected_has_credentials"),
        ),
        sa.CheckConstraint(
            "status IN ('connected', 'needs_reauth', 'disconnected')",
            name=op.f("ck_integrations_status_valid"),
        ),
        sa.CheckConstraint(
            "consecutive_failures >= 0", name=op.f("ck_integrations_failures_not_negative")
        ),
        sa.CheckConstraint(
            "length(trim(external_account_id)) > 0", name=op.f("ck_integrations_account_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["connected_by_user_id"],
            ["users.id"],
            name=op.f("fk_integrations_connected_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_integrations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integrations")),
        sa.UniqueConstraint("organization_id", "id", name="uq_integrations_org_id"),
        sa.UniqueConstraint(
            "organization_id", "provider", "external_account_id", name="uq_integrations_account"
        ),
    )
    op.create_index(
        "ix_integrations_org_provider",
        "integrations",
        ["organization_id", "provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integrations_organization_id"), "integrations", ["organization_id"], unique=False
    )
    op.create_table(
        "integration_syncs",
        sa.Column("integration_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=10), server_default="running", nullable=False),
        sa.Column("trigger", sa.String(length=10), server_default="manual", nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("records_fetched", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("records_created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error_code", sa.String(length=60), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("data_import_id", sa.Uuid(), nullable=True),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status = 'running' OR finished_at IS NOT NULL",
            name=op.f("ck_integration_syncs_finished_has_time"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed')",
            name=op.f("ck_integration_syncs_status_valid"),
        ),
        sa.CheckConstraint(
            "trigger IN ('manual', 'scheduled')", name=op.f("ck_integration_syncs_trigger_valid")
        ),
        sa.CheckConstraint(
            "records_fetched >= 0 AND records_created >= 0",
            name=op.f("ck_integration_syncs_counts_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "data_import_id"],
            ["data_imports.organization_id", "data_imports.id"],
            name=op.f("fk_integration_syncs_organization_id_data_imports"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "integration_id"],
            ["integrations.organization_id", "integrations.id"],
            name=op.f("fk_integration_syncs_organization_id_integrations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_integration_syncs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_integration_syncs_requested_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_syncs")),
    )
    op.create_index(
        "ix_integration_syncs_integration",
        "integration_syncs",
        ["integration_id", "started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_syncs_organization_id"),
        "integration_syncs",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_integration_syncs_organization_id"), table_name="integration_syncs")
    op.drop_index("ix_integration_syncs_integration", table_name="integration_syncs")
    op.drop_table("integration_syncs")
    op.drop_index(op.f("ix_integrations_organization_id"), table_name="integrations")
    op.drop_index("ix_integrations_org_provider", table_name="integrations")
    op.drop_table("integrations")
    op.drop_index(
        op.f("ix_integration_oauth_states_organization_id"), table_name="integration_oauth_states"
    )
    op.drop_index("ix_integration_oauth_states_expires", table_name="integration_oauth_states")
    op.drop_table("integration_oauth_states")
    # ### end Alembic commands ###
