"""trading data tables

Revision ID: d431a4af5525
Revises: acb5c30bed41
Create Date: 2026-09-28 20:51:29.484689
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d431a4af5525"
down_revision: str | None = "acb5c30bed41"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Moved first: the new tables link to (organization_id, id) on business_list_items.
    op.create_unique_constraint(
        "uq_business_list_items_org_id", "business_list_items", ["organization_id", "id"]
    )
    op.create_table(
        "suppliers",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=20), server_default="manual", nullable=False),
        sa.Column("source_ref", sa.String(length=200), nullable=True),
        sa.CheckConstraint(
            "source IN ('manual', 'csv', 'excel', 'xero', 'shopify', 'woocommerce', 'google_analytics')",
            name=op.f("ck_suppliers_source_valid"),
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_suppliers_name_not_blank")),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_suppliers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
        sa.UniqueConstraint("organization_id", "id", name="uq_suppliers_org_id"),
    )
    op.create_index(
        op.f("ix_suppliers_organization_id"), "suppliers", ["organization_id"], unique=False
    )
    op.create_index(
        "uq_suppliers_source_ref",
        "suppliers",
        ["organization_id", "source", "source_ref"],
        unique=True,
        postgresql_where=sa.text("source_ref IS NOT NULL"),
    )
    op.create_table(
        "customers",
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("postcode", sa.String(length=8), nullable=True),
        sa.Column("customer_type_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=20), server_default="manual", nullable=False),
        sa.Column("source_ref", sa.String(length=200), nullable=True),
        sa.CheckConstraint(
            "postcode ~ '^([A-Z]{1,2}[0-9][A-Z0-9]? [0-9][A-Z]{2}|GIR 0AA)$'",
            name=op.f("ck_customers_postcode_format"),
        ),
        sa.CheckConstraint(
            "source IN ('manual', 'csv', 'excel', 'xero', 'shopify', 'woocommerce', 'google_analytics')",
            name=op.f("ck_customers_source_valid"),
        ),
        sa.CheckConstraint("email = lower(email)", name=op.f("ck_customers_email_lowercase")),
        sa.ForeignKeyConstraint(
            ["organization_id", "customer_type_id"],
            ["business_list_items.organization_id", "business_list_items.id"],
            name=op.f("fk_customers_organization_id_business_list_items"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_customers_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("organization_id", "id", name="uq_customers_org_id"),
    )
    op.create_index(
        op.f("ix_customers_organization_id"), "customers", ["organization_id"], unique=False
    )
    op.create_index(
        "uq_customers_source_ref",
        "customers",
        ["organization_id", "source", "source_ref"],
        unique=True,
        postgresql_where=sa.text("source_ref IS NOT NULL"),
    )
    op.create_table(
        "expenses",
        sa.Column("kind", sa.String(length=10), server_default="expense", nullable=False),
        sa.Column("spent_on", sa.Date(), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("cost_category_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column("net_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "vat_amount",
            sa.Numeric(precision=18, scale=4),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("gross_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="GBP", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=20), server_default="manual", nullable=False),
        sa.Column("source_ref", sa.String(length=200), nullable=True),
        sa.CheckConstraint(
            "(kind = 'expense' AND net_amount >= 0 AND vat_amount >= 0) OR (kind = 'credit' AND net_amount <= 0 AND vat_amount <= 0)",
            name=op.f("ck_expenses_sign_matches_kind"),
        ),
        sa.CheckConstraint("currency = 'GBP'", name=op.f("ck_expenses_currency_gbp")),
        sa.CheckConstraint("kind IN ('expense', 'credit')", name=op.f("ck_expenses_kind_valid")),
        sa.CheckConstraint(
            "source IN ('manual', 'csv', 'excel', 'xero', 'shopify', 'woocommerce', 'google_analytics')",
            name=op.f("ck_expenses_source_valid"),
        ),
        sa.CheckConstraint(
            "gross_amount = net_amount + vat_amount", name=op.f("ck_expenses_gross_is_net_plus_vat")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "cost_category_id"],
            ["business_list_items.organization_id", "business_list_items.id"],
            name=op.f("fk_expenses_organization_id_business_list_items"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "supplier_id"],
            ["suppliers.organization_id", "suppliers.id"],
            name=op.f("fk_expenses_organization_id_suppliers"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_expenses_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_expenses")),
        sa.UniqueConstraint("organization_id", "id", name="uq_expenses_org_id"),
    )
    op.create_index(
        "ix_expenses_org_date", "expenses", ["organization_id", "spent_on"], unique=False
    )
    op.create_index(
        op.f("ix_expenses_organization_id"), "expenses", ["organization_id"], unique=False
    )
    op.create_index(
        "uq_expenses_source_ref",
        "expenses",
        ["organization_id", "source", "source_ref"],
        unique=True,
        postgresql_where=sa.text("source_ref IS NOT NULL"),
    )
    op.create_table(
        "products",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("sku", sa.String(length=100), nullable=True),
        sa.Column("offering_id", sa.Uuid(), nullable=True),
        sa.Column("unit_price_ex_vat", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("vat_rate", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=20), server_default="manual", nullable=False),
        sa.Column("source_ref", sa.String(length=200), nullable=True),
        sa.CheckConstraint(
            "source IN ('manual', 'csv', 'excel', 'xero', 'shopify', 'woocommerce', 'google_analytics')",
            name=op.f("ck_products_source_valid"),
        ),
        sa.CheckConstraint("vat_rate IN ('0', '5', '20')", name=op.f("ck_products_vat_rate_uk")),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_products_name_not_blank")),
        sa.CheckConstraint("unit_cost >= 0", name=op.f("ck_products_unit_cost_not_negative")),
        sa.CheckConstraint(
            "unit_price_ex_vat >= 0", name=op.f("ck_products_unit_price_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "offering_id"],
            ["business_list_items.organization_id", "business_list_items.id"],
            name=op.f("fk_products_organization_id_business_list_items"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_products_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("organization_id", "id", name="uq_products_org_id"),
    )
    op.create_index(
        op.f("ix_products_organization_id"), "products", ["organization_id"], unique=False
    )
    op.create_index(
        "uq_products_sku",
        "products",
        ["organization_id", "sku"],
        unique=True,
        postgresql_where=sa.text("sku IS NOT NULL"),
    )
    op.create_index(
        "uq_products_source_ref",
        "products",
        ["organization_id", "source", "source_ref"],
        unique=True,
        postgresql_where=sa.text("source_ref IS NOT NULL"),
    )
    op.create_table(
        "sales",
        sa.Column("kind", sa.String(length=10), server_default="sale", nullable=False),
        sa.Column("sold_on", sa.Date(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.Column("sales_channel_id", sa.Uuid(), nullable=True),
        sa.Column("net_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "vat_amount",
            sa.Numeric(precision=18, scale=4),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("gross_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "discount_amount",
            sa.Numeric(precision=18, scale=4),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), server_default="GBP", nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=20), server_default="manual", nullable=False),
        sa.Column("source_ref", sa.String(length=200), nullable=True),
        sa.CheckConstraint(
            "(kind = 'sale' AND net_amount >= 0 AND vat_amount >= 0) OR (kind = 'refund' AND net_amount <= 0 AND vat_amount <= 0)",
            name=op.f("ck_sales_sign_matches_kind"),
        ),
        sa.CheckConstraint("currency = 'GBP'", name=op.f("ck_sales_currency_gbp")),
        sa.CheckConstraint("kind IN ('sale', 'refund')", name=op.f("ck_sales_kind_valid")),
        sa.CheckConstraint(
            "source IN ('manual', 'csv', 'excel', 'xero', 'shopify', 'woocommerce', 'google_analytics')",
            name=op.f("ck_sales_source_valid"),
        ),
        sa.CheckConstraint("discount_amount >= 0", name=op.f("ck_sales_discount_not_negative")),
        sa.CheckConstraint(
            "gross_amount = net_amount + vat_amount", name=op.f("ck_sales_gross_is_net_plus_vat")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "customer_id"],
            ["customers.organization_id", "customers.id"],
            name=op.f("fk_sales_organization_id_customers"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "sales_channel_id"],
            ["business_list_items.organization_id", "business_list_items.id"],
            name=op.f("fk_sales_organization_id_business_list_items"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sales_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales")),
        sa.UniqueConstraint("organization_id", "id", name="uq_sales_org_id"),
    )
    op.create_index("ix_sales_org_date", "sales", ["organization_id", "sold_on"], unique=False)
    op.create_index(op.f("ix_sales_organization_id"), "sales", ["organization_id"], unique=False)
    op.create_index(
        "uq_sales_source_ref",
        "sales",
        ["organization_id", "source", "source_ref"],
        unique=True,
        postgresql_where=sa.text("source_ref IS NOT NULL"),
    )
    op.create_table(
        "sale_lines",
        sa.Column("sale_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_price_ex_vat", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column(
            "discount_amount",
            sa.Numeric(precision=18, scale=4),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("net_amount", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("vat_rate", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "vat_amount",
            sa.Numeric(precision=18, scale=4),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column("cost_amount", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("vat_rate IN ('0', '5', '20')", name=op.f("ck_sale_lines_vat_rate_uk")),
        sa.CheckConstraint("cost_amount >= 0", name=op.f("ck_sale_lines_cost_not_negative")),
        sa.CheckConstraint(
            "discount_amount >= 0", name=op.f("ck_sale_lines_discount_not_negative")
        ),
        sa.CheckConstraint("quantity <> 0", name=op.f("ck_sale_lines_quantity_not_zero")),
        sa.CheckConstraint(
            "unit_price_ex_vat >= 0", name=op.f("ck_sale_lines_unit_price_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "product_id"],
            ["products.organization_id", "products.id"],
            name=op.f("fk_sale_lines_organization_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "sale_id"],
            ["sales.organization_id", "sales.id"],
            name=op.f("fk_sale_lines_organization_id_sales"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_sale_lines_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sale_lines")),
        sa.UniqueConstraint("organization_id", "id", name="uq_sale_lines_org_id"),
    )
    op.create_index(
        "ix_sale_lines_org_product", "sale_lines", ["organization_id", "product_id"], unique=False
    )
    op.create_index(
        "ix_sale_lines_org_sale", "sale_lines", ["organization_id", "sale_id"], unique=False
    )
    op.create_index(
        op.f("ix_sale_lines_organization_id"), "sale_lines", ["organization_id"], unique=False
    )
    op.create_table(
        "stock_movements",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("moved_on", sa.Date(), nullable=False),
        sa.Column("kind", sa.String(length=12), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("sale_line_id", sa.Uuid(), nullable=True),
        sa.Column("notes", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("source", sa.String(length=20), server_default="manual", nullable=False),
        sa.Column("source_ref", sa.String(length=200), nullable=True),
        sa.CheckConstraint(
            "(kind IN ('opening') AND quantity >= 0) OR (kind IN ('delivery', 'return') AND quantity > 0) OR (kind IN ('sale', 'write_off') AND quantity < 0) OR (kind = 'adjustment' AND quantity <> 0)",
            name=op.f("ck_stock_movements_sign_matches_kind"),
        ),
        sa.CheckConstraint(
            "kind IN ('opening', 'delivery', 'sale', 'return', 'adjustment', 'write_off')",
            name=op.f("ck_stock_movements_kind_valid"),
        ),
        sa.CheckConstraint(
            "source IN ('manual', 'csv', 'excel', 'xero', 'shopify', 'woocommerce', 'google_analytics')",
            name=op.f("ck_stock_movements_source_valid"),
        ),
        sa.CheckConstraint(
            "unit_cost >= 0", name=op.f("ck_stock_movements_unit_cost_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "product_id"],
            ["products.organization_id", "products.id"],
            name=op.f("fk_stock_movements_organization_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "sale_line_id"],
            ["sale_lines.organization_id", "sale_lines.id"],
            name=op.f("fk_stock_movements_organization_id_sale_lines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_stock_movements_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_movements")),
        sa.UniqueConstraint("organization_id", "id", name="uq_stock_movements_org_id"),
    )
    op.create_index(
        "ix_stock_movements_org_product_date",
        "stock_movements",
        ["organization_id", "product_id", "moved_on"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_movements_organization_id"),
        "stock_movements",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "uq_stock_movements_source_ref",
        "stock_movements",
        ["organization_id", "source", "source_ref"],
        unique=True,
        postgresql_where=sa.text("source_ref IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_stock_movements_source_ref",
        table_name="stock_movements",
        postgresql_where=sa.text("source_ref IS NOT NULL"),
    )
    op.drop_index(op.f("ix_stock_movements_organization_id"), table_name="stock_movements")
    op.drop_index("ix_stock_movements_org_product_date", table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_index(op.f("ix_sale_lines_organization_id"), table_name="sale_lines")
    op.drop_index("ix_sale_lines_org_sale", table_name="sale_lines")
    op.drop_index("ix_sale_lines_org_product", table_name="sale_lines")
    op.drop_table("sale_lines")
    op.drop_index(
        "uq_sales_source_ref",
        table_name="sales",
        postgresql_where=sa.text("source_ref IS NOT NULL"),
    )
    op.drop_index(op.f("ix_sales_organization_id"), table_name="sales")
    op.drop_index("ix_sales_org_date", table_name="sales")
    op.drop_table("sales")
    op.drop_index(
        "uq_products_source_ref",
        table_name="products",
        postgresql_where=sa.text("source_ref IS NOT NULL"),
    )
    op.drop_index(
        "uq_products_sku", table_name="products", postgresql_where=sa.text("sku IS NOT NULL")
    )
    op.drop_index(op.f("ix_products_organization_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(
        "uq_expenses_source_ref",
        table_name="expenses",
        postgresql_where=sa.text("source_ref IS NOT NULL"),
    )
    op.drop_index(op.f("ix_expenses_organization_id"), table_name="expenses")
    op.drop_index("ix_expenses_org_date", table_name="expenses")
    op.drop_table("expenses")
    op.drop_index(
        "uq_customers_source_ref",
        table_name="customers",
        postgresql_where=sa.text("source_ref IS NOT NULL"),
    )
    op.drop_index(op.f("ix_customers_organization_id"), table_name="customers")
    op.drop_table("customers")
    op.drop_index(
        "uq_suppliers_source_ref",
        table_name="suppliers",
        postgresql_where=sa.text("source_ref IS NOT NULL"),
    )
    op.drop_index(op.f("ix_suppliers_organization_id"), table_name="suppliers")
    op.drop_table("suppliers")
    # Last: only once nothing links to (organization_id, id) any more.
    op.drop_constraint("uq_business_list_items_org_id", "business_list_items", type_="unique")
    # ### end Alembic commands ###
