"""billing tables

Revision ID: 3901814eab37
Revises: 1b6ad17eb684
Create Date: 2026-10-09 18:29:50.784799
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "3901814eab37"
down_revision: str | None = "1b6ad17eb684"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plans",
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=False),
        sa.Column("price_month_pence", sa.Integer(), nullable=True),
        sa.Column("price_year_pence", sa.Integer(), nullable=True),
        sa.Column("currency", sa.String(length=3), server_default="GBP", nullable=False),
        sa.Column("self_serve", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_public", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "provider_prices",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("code ~ '^[a-z][a-z0-9_]*$'", name=op.f("ck_plans_code_format")),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f("ck_plans_currency_format")),
        sa.CheckConstraint(
            "NOT self_serve OR price_month_pence IS NOT NULL",
            name=op.f("ck_plans_self_serve_has_a_price"),
        ),
        sa.CheckConstraint("length(trim(name)) > 0", name=op.f("ck_plans_name_not_blank")),
        sa.CheckConstraint(
            "price_month_pence IS NULL OR price_month_pence >= 0",
            name=op.f("ck_plans_month_price_valid"),
        ),
        sa.CheckConstraint(
            "price_year_pence IS NULL OR price_year_pence >= 0",
            name=op.f("ck_plans_year_price_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plans")),
        sa.UniqueConstraint("code", name="uq_plans_code"),
    )
    op.create_table(
        "feature_entitlements",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("feature", sa.String(length=30), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("limit", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "feature IN ('members', 'integrations', 'scheduled_reports', 'ai_assistant')",
            name=op.f("ck_feature_entitlements_feature_valid"),
        ),
        sa.CheckConstraint(
            '"limit" IS NULL OR "limit" >= 0',
            name=op.f("ck_feature_entitlements_limit_not_negative"),
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["plans.id"],
            name=op.f("fk_feature_entitlements_plan_id_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_entitlements")),
        sa.UniqueConstraint("plan_id", "feature", name="uq_feature_entitlements_plan_feature"),
    )
    op.create_table(
        "billing_events",
        sa.Column("provider", sa.String(length=15), nullable=False),
        sa.Column("event_id", sa.String(length=160), nullable=False),
        sa.Column("type", sa.String(length=60), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column(
            "detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('processed', 'ignored', 'failed')",
            name=op.f("ck_billing_events_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_billing_events_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_events")),
        sa.UniqueConstraint("provider", "event_id", name="uq_billing_events_provider_event"),
    )
    op.create_index(
        "ix_billing_events_org", "billing_events", ["organization_id", "received_at"], unique=False
    )
    op.create_index(
        op.f("ix_billing_events_organization_id"),
        "billing_events",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "subscriptions",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("scheduled_plan_id", sa.Uuid(), nullable=True),
        sa.Column("scheduled_interval", sa.String(length=5), nullable=True),
        sa.Column("status", sa.String(length=15), nullable=False),
        sa.Column("interval", sa.String(length=5), server_default="month", nullable=False),
        sa.Column("provider", sa.String(length=15), server_default="none", nullable=False),
        sa.Column("provider_customer_id", sa.String(length=120), nullable=True),
        sa.Column("provider_subscription_id", sa.String(length=120), nullable=True),
        sa.Column("trial_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "cancel_at_period_end", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("canceled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "interval IN ('month', 'year')", name=op.f("ck_subscriptions_interval_valid")
        ),
        sa.CheckConstraint(
            "provider IN ('none', 'sandbox', 'stripe', 'paystack')",
            name=op.f("ck_subscriptions_provider_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('trialing', 'active', 'past_due', 'canceled', 'expired')",
            name=op.f("ck_subscriptions_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_subscriptions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plans.id"], name=op.f("fk_subscriptions_plan_id_plans")
        ),
        sa.ForeignKeyConstraint(
            ["scheduled_plan_id"],
            ["plans.id"],
            name=op.f("fk_subscriptions_scheduled_plan_id_plans"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint("organization_id", "id", name="uq_subscriptions_org_id"),
        sa.UniqueConstraint("organization_id", name="uq_subscriptions_organization"),
    )
    op.create_index(
        "ix_subscriptions_customer",
        "subscriptions",
        ["provider", "provider_customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscriptions_organization_id"), "subscriptions", ["organization_id"], unique=False
    )
    op.create_index(
        "uq_subscriptions_provider_ref",
        "subscriptions",
        ["provider", "provider_subscription_id"],
        unique=True,
        postgresql_where=sa.text("provider_subscription_id IS NOT NULL"),
    )
    op.create_table(
        "invoices",
        sa.Column("subscription_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=15), nullable=False),
        sa.Column("provider_invoice_id", sa.String(length=120), nullable=False),
        sa.Column("number", sa.String(length=60), nullable=True),
        sa.Column("status", sa.String(length=15), nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="GBP", nullable=False),
        sa.Column("net_pence", sa.BigInteger(), nullable=False),
        sa.Column("vat_pence", sa.BigInteger(), nullable=False),
        sa.Column("total_pence", sa.BigInteger(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hosted_url", sa.String(length=500), nullable=True),
        sa.Column(
            "lines",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provider IN ('none', 'sandbox', 'stripe', 'paystack')",
            name=op.f("ck_invoices_provider_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'open', 'paid', 'void', 'uncollectible')",
            name=op.f("ck_invoices_status_valid"),
        ),
        sa.CheckConstraint(
            "net_pence >= 0 AND vat_pence >= 0", name=op.f("ck_invoices_amounts_not_negative")
        ),
        sa.CheckConstraint(
            "total_pence = net_pence + vat_pence", name=op.f("ck_invoices_total_adds_up")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_invoices_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_invoices_subscription_id_subscriptions"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invoices")),
        sa.UniqueConstraint("provider", "provider_invoice_id", name="uq_invoices_provider_ref"),
    )
    op.create_index(
        "ix_invoices_org_issued", "invoices", ["organization_id", "issued_at"], unique=False
    )
    op.create_index(
        op.f("ix_invoices_organization_id"), "invoices", ["organization_id"], unique=False
    )
    op.create_table(
        "subscription_items",
        sa.Column("subscription_id", sa.Uuid(), nullable=False),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.String(length=200), nullable=False),
        sa.Column("quantity", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("unit_amount_pence", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('plan', 'extra')", name=op.f("ck_subscription_items_kind_valid")
        ),
        sa.CheckConstraint("quantity >= 1", name=op.f("ck_subscription_items_quantity_positive")),
        sa.CheckConstraint(
            "unit_amount_pence >= 0", name=op.f("ck_subscription_items_amount_not_negative")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_subscription_items_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plans.id"], name=op.f("fk_subscription_items_plan_id_plans")
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_subscription_items_subscription_id_subscriptions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscription_items")),
    )
    op.create_index(
        op.f("ix_subscription_items_organization_id"),
        "subscription_items",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_subscription_items_subscription_id"),
        "subscription_items",
        ["subscription_id"],
        unique=False,
    )
    # The four plans from the proposal. EVERY PRICE AND LIMIT HERE IS A PLACEHOLDER to be confirmed
    # before launch: they are rows, so they can be changed without touching the code.
    plans = sa.table(
        "plans",
        sa.column("id", sa.Uuid),
        sa.column("code", sa.String),
        sa.column("name", sa.String),
        sa.column("description", sa.String),
        sa.column("price_month_pence", sa.Integer),
        sa.column("price_year_pence", sa.Integer),
        sa.column("self_serve", sa.Boolean),
        sa.column("sort_order", sa.SmallInteger),
    )
    entitlements = sa.table(
        "feature_entitlements",
        sa.column("id", sa.Uuid),
        sa.column("plan_id", sa.Uuid),
        sa.column("feature", sa.String),
        sa.column("enabled", sa.Boolean),
        sa.column("limit", sa.Integer),
    )
    import uuid as _uuid

    catalogue = [
        (
            "starter",
            "Starter",
            "For a small business getting started.",
            9900,
            99000,
            True,
            1,
            (3, 1, 1, False),
        ),
        (
            "growth",
            "Growth",
            "For a growing team that wants help from the assistant.",
            19900,
            199000,
            True,
            2,
            (10, 3, 5, True),
        ),
        (
            "scale",
            "Scale",
            "For a busy business with a bigger team and more connections.",
            29900,
            299000,
            True,
            3,
            (25, 10, 20, True),
        ),
        (
            "corporate",
            "Corporate",
            "For larger organisations: talk to us.",
            None,
            None,
            False,
            4,
            (None, None, None, True),
        ),
    ]  # members, integrations, scheduled reports, assistant
    for code, name, description, month, year, self_serve, order, (
        members,
        integrations,
        schedules,
        assistant,
    ) in catalogue:
        plan_id = _uuid.uuid4()
        op.bulk_insert(
            plans,
            [
                {
                    "id": plan_id,
                    "code": code,
                    "name": name,
                    "description": description,
                    "price_month_pence": month,
                    "price_year_pence": year,
                    "self_serve": self_serve,
                    "sort_order": order,
                }
            ],
        )
        op.bulk_insert(
            entitlements,
            [
                {
                    "id": _uuid.uuid4(),
                    "plan_id": plan_id,
                    "feature": "members",
                    "enabled": True,
                    "limit": members,
                },
                {
                    "id": _uuid.uuid4(),
                    "plan_id": plan_id,
                    "feature": "integrations",
                    "enabled": True,
                    "limit": integrations,
                },
                {
                    "id": _uuid.uuid4(),
                    "plan_id": plan_id,
                    "feature": "scheduled_reports",
                    "enabled": True,
                    "limit": schedules,
                },
                {
                    "id": _uuid.uuid4(),
                    "plan_id": plan_id,
                    "feature": "ai_assistant",
                    "enabled": assistant,
                    "limit": None,
                },
            ],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscription_items_subscription_id"), table_name="subscription_items")
    op.drop_index(op.f("ix_subscription_items_organization_id"), table_name="subscription_items")
    op.drop_table("subscription_items")
    op.drop_index(op.f("ix_invoices_organization_id"), table_name="invoices")
    op.drop_index("ix_invoices_org_issued", table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(
        "uq_subscriptions_provider_ref",
        table_name="subscriptions",
        postgresql_where=sa.text("provider_subscription_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_subscriptions_organization_id"), table_name="subscriptions")
    op.drop_index("ix_subscriptions_customer", table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_billing_events_organization_id"), table_name="billing_events")
    op.drop_index("ix_billing_events_org", table_name="billing_events")
    op.drop_table("billing_events")
    op.drop_table("feature_entitlements")
    op.drop_table("plans")
    # ### end Alembic commands ###
