"""import validation summary

Revision ID: 5089674c18c9
Revises: 6cb8930fcbc1
Create Date: 2026-10-01 15:04:53.724329
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "5089674c18c9"
down_revision: str | None = "6cb8930fcbc1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_imports",
        sa.Column(
            "validation_summary",
            postgresql.JSONB(none_as_null=True, astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_imports", "validation_summary")
    # ### end Alembic commands ###
