"""sale lines record their import

Revision ID: 0fde7caa9661
Revises: 1dc2737c9ab6
Create Date: 2026-10-01 22:51:42.106120
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0fde7caa9661"
down_revision: str | None = "1dc2737c9ab6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sale_lines", sa.Column("import_id", sa.Uuid(), nullable=True))
    # Lines already stored take the import of the sale they belong to.
    op.execute(
        """
        UPDATE sale_lines
        SET import_id = sales.import_id
        FROM sales
        WHERE sales.organization_id = sale_lines.organization_id
          AND sales.id = sale_lines.sale_id
          AND sales.import_id IS NOT NULL
        """
    )
    op.create_index(
        "ix_sale_lines_org_import", "sale_lines", ["organization_id", "import_id"], unique=False
    )
    op.create_foreign_key(
        op.f("fk_sale_lines_organization_id_data_imports"),
        "sale_lines",
        "data_imports",
        ["organization_id", "import_id"],
        ["organization_id", "id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_sale_lines_organization_id_data_imports"), "sale_lines", type_="foreignkey"
    )
    op.drop_index("ix_sale_lines_org_import", table_name="sale_lines")
    op.drop_column("sale_lines", "import_id")
    # ### end Alembic commands ###
