"""kpi tables

Revision ID: db987911b622
Revises: a27cdf228a45
Create Date: 2026-10-02 20:25:53.767487
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "db987911b622"
down_revision: str | None = "a27cdf228a45"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kpi_definitions",
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=400), nullable=False),
        sa.Column("category", sa.String(length=15), nullable=False),
        sa.Column("unit", sa.String(length=10), nullable=False),
        sa.Column("expression", sa.Text(), nullable=False),
        sa.Column("direction", sa.String(length=10), server_default="neutral", nullable=False),
        sa.Column(
            "requires",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("industry_code", sa.String(length=50), nullable=True),
        sa.Column("sort_order", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('financial', 'sales', 'customer', 'marketing', 'inventory', 'operational')",
            name=op.f("ck_kpi_definitions_category_valid"),
        ),
        sa.CheckConstraint(
            "code ~ '^[a-z][a-z0-9_]*$'", name=op.f("ck_kpi_definitions_code_format")
        ),
        sa.CheckConstraint(
            "direction IN ('up_good', 'down_good', 'neutral')",
            name=op.f("ck_kpi_definitions_direction_valid"),
        ),
        sa.CheckConstraint(
            "unit IN ('gbp', 'percent', 'count', 'ratio')",
            name=op.f("ck_kpi_definitions_unit_valid"),
        ),
        sa.CheckConstraint(
            "length(trim(expression)) > 0", name=op.f("ck_kpi_definitions_expression_not_blank")
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0", name=op.f("ck_kpi_definitions_name_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["industry_code"],
            ["industries.code"],
            name=op.f("fk_kpi_definitions_industry_code_industries"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kpi_definitions")),
        sa.UniqueConstraint("code", name="uq_kpi_definitions_code"),
    )
    op.create_index(
        "ix_kpi_definitions_category", "kpi_definitions", ["category", "sort_order"], unique=False
    )
    op.create_table(
        "kpi_calculation_runs",
        sa.Column("status", sa.String(length=10), server_default="running", nullable=False),
        sa.Column("trigger", sa.String(length=10), server_default="manual", nullable=False),
        sa.Column("granularity", sa.String(length=10), nullable=False),
        sa.Column("period_from", sa.Date(), nullable=False),
        sa.Column("period_to", sa.Date(), nullable=False),
        sa.Column("kpi_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("values_written", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("requested_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("job_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "granularity IN ('week', 'month', 'quarter', 'year')",
            name=op.f("ck_kpi_calculation_runs_granularity_valid"),
        ),
        sa.CheckConstraint(
            "status = 'running' OR finished_at IS NOT NULL",
            name=op.f("ck_kpi_calculation_runs_finished_has_time"),
        ),
        sa.CheckConstraint(
            "status IN ('running', 'succeeded', 'failed')",
            name=op.f("ck_kpi_calculation_runs_status_valid"),
        ),
        sa.CheckConstraint(
            "trigger IN ('manual', 'import')", name=op.f("ck_kpi_calculation_runs_trigger_valid")
        ),
        sa.CheckConstraint(
            "period_to >= period_from", name=op.f("ck_kpi_calculation_runs_period_in_order")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_kpi_calculation_runs_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_user_id"],
            ["users.id"],
            name=op.f("fk_kpi_calculation_runs_requested_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kpi_calculation_runs")),
        sa.UniqueConstraint("organization_id", "id", name="uq_kpi_calculation_runs_org_id"),
    )
    op.create_index(
        "ix_kpi_calculation_runs_org_started",
        "kpi_calculation_runs",
        ["organization_id", "started_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kpi_calculation_runs_organization_id"),
        "kpi_calculation_runs",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "kpi_values",
        sa.Column("kpi_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("granularity", sa.String(length=10), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("is_complete", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=10), server_default="ok", nullable=False),
        sa.Column("value", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("previous_value", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("change_pct", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("data_quality", sa.SmallInteger(), nullable=True),
        sa.Column(
            "inputs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "granularity IN ('week', 'month', 'quarter', 'year')",
            name=op.f("ck_kpi_values_granularity_valid"),
        ),
        sa.CheckConstraint(
            "status = 'ok' OR value IS NULL", name=op.f("ck_kpi_values_only_ok_has_value")
        ),
        sa.CheckConstraint(
            "status IN ('ok', 'no_data', 'undefined')", name=op.f("ck_kpi_values_status_valid")
        ),
        sa.CheckConstraint(
            "data_quality IS NULL OR data_quality BETWEEN 0 AND 100",
            name=op.f("ck_kpi_values_quality_in_range"),
        ),
        sa.CheckConstraint(
            "period_end >= period_start", name=op.f("ck_kpi_values_period_in_order")
        ),
        sa.ForeignKeyConstraint(
            ["kpi_id"], ["kpi_definitions.id"], name=op.f("fk_kpi_values_kpi_id_kpi_definitions")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "run_id"],
            ["kpi_calculation_runs.organization_id", "kpi_calculation_runs.id"],
            name=op.f("fk_kpi_values_organization_id_kpi_calculation_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_kpi_values_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kpi_values")),
        sa.UniqueConstraint(
            "organization_id", "kpi_id", "granularity", "period_start", name="uq_kpi_values_period"
        ),
    )
    op.create_index("ix_kpi_values_kpi", "kpi_values", ["kpi_id"], unique=False)
    op.create_index(
        "ix_kpi_values_org_period",
        "kpi_values",
        ["organization_id", "granularity", "period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_kpi_values_organization_id"), "kpi_values", ["organization_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_kpi_values_organization_id"), table_name="kpi_values")
    op.drop_index("ix_kpi_values_org_period", table_name="kpi_values")
    op.drop_index("ix_kpi_values_kpi", table_name="kpi_values")
    op.drop_table("kpi_values")
    op.drop_index(
        op.f("ix_kpi_calculation_runs_organization_id"), table_name="kpi_calculation_runs"
    )
    op.drop_index("ix_kpi_calculation_runs_org_started", table_name="kpi_calculation_runs")
    op.drop_table("kpi_calculation_runs")
    op.drop_index("ix_kpi_definitions_category", table_name="kpi_definitions")
    op.drop_table("kpi_definitions")
    # ### end Alembic commands ###
