"""diagnosis rules version and basis

Revision ID: 4d327fab7428
Revises: f8ea47f386e8
Create Date: 2026-10-04 08:45:19.014947
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '4d327fab7428'
down_revision: str | None = 'f8ea47f386e8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnoses', sa.Column('confidence_note', sa.Text(), nullable=True))
    op.add_column('diagnoses', sa.Column('rules_version', sa.String(length=30), server_default='diagnosis-1', nullable=False))
    op.add_column('diagnoses', sa.Column('basis', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnoses', 'basis')
    op.drop_column('diagnoses', 'rules_version')
    op.drop_column('diagnoses', 'confidence_note')
    # ### end Alembic commands ###
