"""mobile sessions and push devices

Revision ID: d228cdd9e926
Revises: 7f55338ae22a
Create Date: 2026-10-10 10:24:02.850714
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d228cdd9e926"
down_revision: str | None = "7f55338ae22a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "push_devices",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=True),
        sa.Column("platform", sa.String(length=10), nullable=False),
        sa.Column("token", sa.String(length=4096), nullable=False),
        sa.Column("app_version", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "platform IN ('ios', 'android')", name=op.f("ck_push_devices_platform_valid")
        ),
        sa.CheckConstraint("length(token) >= 20", name=op.f("ck_push_devices_token_long_enough")),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["user_sessions.id"],
            name=op.f("fk_push_devices_session_id_user_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_push_devices_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_push_devices")),
        sa.UniqueConstraint("token", name=op.f("uq_push_devices_token")),
    )
    op.create_index(
        "ix_push_devices_user", "push_devices", ["user_id", "last_seen_at"], unique=False
    )
    op.add_column(
        "user_sessions",
        sa.Column("client", sa.String(length=10), server_default="web", nullable=False),
    )
    op.add_column("user_sessions", sa.Column("device_name", sa.String(length=100), nullable=True))
    op.create_check_constraint(
        op.f("ck_user_sessions_client_valid"), "user_sessions", "client IN ('web', 'mobile')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_user_sessions_client_valid"), "user_sessions", type_="check")
    op.drop_column("user_sessions", "device_name")
    op.drop_column("user_sessions", "client")
    op.drop_index("ix_push_devices_user", table_name="push_devices")
    op.drop_table("push_devices")
    # ### end Alembic commands ###
