"""recommendation tables

Revision ID: be176f3d1b2e
Revises: 8a249b9dff78
Create Date: 2026-10-04 18:53:44.244395
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "be176f3d1b2e"
down_revision: str | None = "8a249b9dff78"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "intervention_library",
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("category", sa.String(length=15), nullable=False),
        sa.Column("summary", sa.String(length=400), nullable=False),
        sa.Column(
            "steps",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "addresses",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "kpis",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column(
            "goal_types",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'"),
            nullable=False,
        ),
        sa.Column("effort", sa.String(length=10), nullable=False),
        sa.Column("cost_level", sa.String(length=10), nullable=False),
        sa.Column("typical_days_to_effect", sa.SmallInteger(), nullable=False),
        sa.Column("impact_share", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("impact_basis", sa.String(length=300), nullable=False),
        sa.Column("version", sa.String(length=20), server_default="1", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('financial', 'sales', 'customer', 'marketing', 'inventory', 'operational')",
            name=op.f("ck_intervention_library_category_valid"),
        ),
        sa.CheckConstraint(
            "code ~ '^[a-z][a-z0-9_]*$'", name=op.f("ck_intervention_library_code_format")
        ),
        sa.CheckConstraint(
            "cost_level IN ('none', 'low', 'medium', 'high')",
            name=op.f("ck_intervention_library_cost_valid"),
        ),
        sa.CheckConstraint(
            "effort IN ('low', 'medium', 'high')", name=op.f("ck_intervention_library_effort_valid")
        ),
        sa.CheckConstraint(
            "impact_share BETWEEN 0 AND 1", name=op.f("ck_intervention_library_impact_share_range")
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0", name=op.f("ck_intervention_library_name_not_blank")
        ),
        sa.CheckConstraint(
            "typical_days_to_effect >= 0", name=op.f("ck_intervention_library_days_not_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_intervention_library")),
        sa.UniqueConstraint("code", name="uq_intervention_library_code"),
    )
    op.create_table(
        "recommendations",
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column("diagnosis_id", sa.Uuid(), nullable=True),
        sa.Column("status", sa.String(length=25), server_default="open", nullable=False),
        sa.Column("headline", sa.String(length=300), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("rules_version", sa.String(length=30), nullable=False),
        sa.Column(
            "basis",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('open', 'no_action_needed', 'insufficient_evidence', 'dismissed')",
            name=op.f("ck_recommendations_status_valid"),
        ),
        sa.CheckConstraint(
            "length(trim(headline)) > 0", name=op.f("ck_recommendations_headline_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "diagnosis_id"],
            ["diagnoses.organization_id", "diagnoses.id"],
            name=op.f("fk_recommendations_organization_id_diagnoses"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "event_id"],
            ["detection_events.organization_id", "detection_events.id"],
            name=op.f("fk_recommendations_organization_id_detection_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_recommendations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendations")),
        sa.UniqueConstraint("event_id", name="uq_recommendations_event"),
        sa.UniqueConstraint("organization_id", "id", name="uq_recommendations_org_id"),
    )
    op.create_index(
        op.f("ix_recommendations_organization_id"),
        "recommendations",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "recommendation_evidence",
        sa.Column("recommendation_id", sa.Uuid(), nullable=False),
        sa.Column("evidence_type", sa.String(length=20), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("sort_order", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "evidence_type IN ('fact', 'statistical', 'ai_interpretation', 'insufficient')",
            name=op.f("ck_recommendation_evidence_evidence_type_valid"),
        ),
        sa.CheckConstraint(
            "length(trim(statement)) > 0",
            name=op.f("ck_recommendation_evidence_statement_not_blank"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "recommendation_id"],
            ["recommendations.organization_id", "recommendations.id"],
            name=op.f("fk_recommendation_evidence_organization_id_recommendations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_recommendation_evidence_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation_evidence")),
    )
    op.create_index(
        op.f("ix_recommendation_evidence_organization_id"),
        "recommendation_evidence",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_recommendation_evidence_recommendation",
        "recommendation_evidence",
        ["recommendation_id", "sort_order"],
        unique=False,
    )
    op.create_table(
        "recommendation_options",
        sa.Column("recommendation_id", sa.Uuid(), nullable=False),
        sa.Column("intervention_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.SmallInteger(), nullable=False),
        sa.Column("is_recommended", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("target_label", sa.String(length=200), nullable=True),
        sa.Column("impact_value", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("impact_unit", sa.String(length=10), nullable=False),
        sa.Column("impact_score", sa.SmallInteger(), nullable=False),
        sa.Column("confidence", sa.SmallInteger(), nullable=False),
        sa.Column("goal_fit", sa.SmallInteger(), nullable=False),
        sa.Column("urgency", sa.SmallInteger(), nullable=False),
        sa.Column("ease", sa.SmallInteger(), nullable=False),
        sa.Column("history_score", sa.SmallInteger(), nullable=False),
        sa.Column("total_score", sa.SmallInteger(), nullable=False),
        sa.Column("effort", sa.String(length=10), nullable=False),
        sa.Column("cost_level", sa.String(length=10), nullable=False),
        sa.Column("days_to_effect", sa.SmallInteger(), nullable=False),
        sa.Column(
            "breakdown",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "cost_level IN ('none', 'low', 'medium', 'high')",
            name=op.f("ck_recommendation_options_cost_valid"),
        ),
        sa.CheckConstraint(
            "effort IN ('low', 'medium', 'high')",
            name=op.f("ck_recommendation_options_effort_valid"),
        ),
        sa.CheckConstraint(
            "NOT is_recommended OR rank = 1",
            name=op.f("ck_recommendation_options_recommended_is_first"),
        ),
        sa.CheckConstraint(
            "confidence BETWEEN 0 AND 100 AND goal_fit BETWEEN 0 AND 100 AND urgency BETWEEN 0 AND 100 AND ease BETWEEN 0 AND 100 AND impact_score BETWEEN 0 AND 100 AND history_score BETWEEN 0 AND 100 AND total_score BETWEEN 0 AND 100",
            name=op.f("ck_recommendation_options_scores_in_range"),
        ),
        sa.CheckConstraint("rank >= 1", name=op.f("ck_recommendation_options_rank_positive")),
        sa.ForeignKeyConstraint(
            ["intervention_id"],
            ["intervention_library.id"],
            name=op.f("fk_recommendation_options_intervention_id_intervention_library"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "recommendation_id"],
            ["recommendations.organization_id", "recommendations.id"],
            name=op.f("fk_recommendation_options_organization_id_recommendations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_recommendation_options_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_recommendation_options")),
        sa.UniqueConstraint("organization_id", "id", name="uq_recommendation_options_org_id"),
        sa.UniqueConstraint("recommendation_id", "rank", name="uq_recommendation_options_rank"),
    )
    op.create_index(
        op.f("ix_recommendation_options_organization_id"),
        "recommendation_options",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        "ix_recommendation_options_recommendation",
        "recommendation_options",
        ["recommendation_id", "rank"],
        unique=False,
    )
    op.create_index(
        "uq_recommendation_options_recommended",
        "recommendation_options",
        ["recommendation_id"],
        unique=True,
        postgresql_where=sa.text("is_recommended"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_recommendation_options_recommended",
        table_name="recommendation_options",
        postgresql_where=sa.text("is_recommended"),
    )
    op.drop_index("ix_recommendation_options_recommendation", table_name="recommendation_options")
    op.drop_index(
        op.f("ix_recommendation_options_organization_id"), table_name="recommendation_options"
    )
    op.drop_table("recommendation_options")
    op.drop_index("ix_recommendation_evidence_recommendation", table_name="recommendation_evidence")
    op.drop_index(
        op.f("ix_recommendation_evidence_organization_id"), table_name="recommendation_evidence"
    )
    op.drop_table("recommendation_evidence")
    op.drop_index(op.f("ix_recommendations_organization_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_table("intervention_library")
    # ### end Alembic commands ###
