"""forecast tables

Revision ID: c7de7630cc0f
Revises: 4d327fab7428
Create Date: 2026-10-04 10:07:13.243461
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c7de7630cc0f"
down_revision: str | None = "4d327fab7428"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forecast_models",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=400), nullable=False),
        sa.Column("version", sa.String(length=20), server_default="1", nullable=False),
        sa.Column("min_history", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "code ~ '^[a-z][a-z0-9_]*$'", name=op.f("ck_forecast_models_code_format")
        ),
        sa.CheckConstraint(
            "length(trim(name)) > 0", name=op.f("ck_forecast_models_name_not_blank")
        ),
        sa.CheckConstraint(
            "min_history >= 1", name=op.f("ck_forecast_models_min_history_positive")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_models")),
        sa.UniqueConstraint("code", name="uq_forecast_models_code"),
    )
    op.create_table(
        "forecasts",
        sa.Column("kpi_id", sa.Uuid(), nullable=False),
        sa.Column("granularity", sa.String(length=10), server_default="month", nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("horizon", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("model_id", sa.Uuid(), nullable=True),
        sa.Column("model_version", sa.String(length=20), nullable=True),
        sa.Column(
            "interval_level", sa.SmallInteger(), server_default=sa.text("80"), nullable=False
        ),
        sa.Column("history_months", sa.Integer(), nullable=False),
        sa.Column(
            "adjusted_for_seasons", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column(
            "inputs",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("calculated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("granularity = 'month'", name=op.f("ck_forecasts_granularity_valid")),
        sa.CheckConstraint(
            "status <> 'ok' OR model_id IS NOT NULL", name=op.f("ck_forecasts_ok_has_model")
        ),
        sa.CheckConstraint(
            "status IN ('ok', 'insufficient_data')", name=op.f("ck_forecasts_status_valid")
        ),
        sa.CheckConstraint("history_months >= 0", name=op.f("ck_forecasts_history_not_negative")),
        sa.CheckConstraint("horizon BETWEEN 1 AND 12", name=op.f("ck_forecasts_horizon_range")),
        sa.CheckConstraint(
            "interval_level BETWEEN 50 AND 99", name=op.f("ck_forecasts_interval_level_range")
        ),
        sa.ForeignKeyConstraint(
            ["kpi_id"], ["kpi_definitions.id"], name=op.f("fk_forecasts_kpi_id_kpi_definitions")
        ),
        sa.ForeignKeyConstraint(
            ["model_id"], ["forecast_models.id"], name=op.f("fk_forecasts_model_id_forecast_models")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_forecasts_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecasts")),
        sa.UniqueConstraint("organization_id", "id", name="uq_forecasts_org_id"),
        sa.UniqueConstraint(
            "organization_id", "kpi_id", "granularity", "as_of", name="uq_forecasts_kpi_as_of"
        ),
    )
    op.create_index(
        "ix_forecasts_org_kpi", "forecasts", ["organization_id", "kpi_id", "as_of"], unique=False
    )
    op.create_index(
        op.f("ix_forecasts_organization_id"), "forecasts", ["organization_id"], unique=False
    )
    op.create_table(
        "forecast_evaluations",
        sa.Column("forecast_id", sa.Uuid(), nullable=False),
        sa.Column("model_code", sa.String(length=40), nullable=False),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("mae", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("rmse", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("mape", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("n_points", sa.SmallInteger(), nullable=False),
        sa.Column("is_chosen", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "method IN ('backtest', 'actual')", name=op.f("ck_forecast_evaluations_method_valid")
        ),
        sa.CheckConstraint(
            "mae >= 0 AND rmse >= 0", name=op.f("ck_forecast_evaluations_errors_not_negative")
        ),
        sa.CheckConstraint("n_points >= 1", name=op.f("ck_forecast_evaluations_points_positive")),
        sa.ForeignKeyConstraint(
            ["organization_id", "forecast_id"],
            ["forecasts.organization_id", "forecasts.id"],
            name=op.f("fk_forecast_evaluations_organization_id_forecasts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_forecast_evaluations_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_evaluations")),
        sa.UniqueConstraint(
            "forecast_id", "model_code", "method", name="uq_forecast_evaluations_model_method"
        ),
    )
    op.create_index(
        "ix_forecast_evaluations_forecast", "forecast_evaluations", ["forecast_id"], unique=False
    )
    op.create_index(
        op.f("ix_forecast_evaluations_organization_id"),
        "forecast_evaluations",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "forecast_predictions",
        sa.Column("forecast_id", sa.Uuid(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("value", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("lower_value", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("upper_value", sa.Numeric(precision=24, scale=6), nullable=False),
        sa.Column("actual_value", sa.Numeric(precision=24, scale=6), nullable=True),
        sa.Column("actual_recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "lower_value <= value AND value <= upper_value",
            name=op.f("ck_forecast_predictions_range_holds_value"),
        ),
        sa.CheckConstraint(
            "period_end >= period_start", name=op.f("ck_forecast_predictions_period_in_order")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id", "forecast_id"],
            ["forecasts.organization_id", "forecasts.id"],
            name=op.f("fk_forecast_predictions_organization_id_forecasts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_forecast_predictions_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_predictions")),
        sa.UniqueConstraint("forecast_id", "period_start", name="uq_forecast_predictions_period"),
    )
    op.create_index(
        "ix_forecast_predictions_forecast",
        "forecast_predictions",
        ["forecast_id", "period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_forecast_predictions_organization_id"),
        "forecast_predictions",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_forecast_predictions_organization_id"), table_name="forecast_predictions"
    )
    op.drop_index("ix_forecast_predictions_forecast", table_name="forecast_predictions")
    op.drop_table("forecast_predictions")
    op.drop_index(
        op.f("ix_forecast_evaluations_organization_id"), table_name="forecast_evaluations"
    )
    op.drop_index("ix_forecast_evaluations_forecast", table_name="forecast_evaluations")
    op.drop_table("forecast_evaluations")
    op.drop_index(op.f("ix_forecasts_organization_id"), table_name="forecasts")
    op.drop_index("ix_forecasts_org_kpi", table_name="forecasts")
    op.drop_table("forecasts")
    op.drop_table("forecast_models")
    # ### end Alembic commands ###
