"""assistant tables

Revision ID: 244c43b07705
Revises: 27af5a64e938
Create Date: 2026-10-05 14:23:03.043765
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '244c43b07705'
down_revision: str | None = '27af5a64e938'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_model_versions',
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('offline', 'anthropic')", name=op.f('ck_ai_model_versions_provider_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_model_versions')),
    sa.UniqueConstraint('provider', 'model', 'version', name='uq_ai_model_versions_key')
    )
    op.create_table('ai_settings',
    sa.Column('ai_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('allow_external_ai', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('allow_model_improvement', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_settings_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by_user_id'], ['users.id'], name=op.f('fk_ai_settings_updated_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_settings')),
    sa.UniqueConstraint('organization_id', name='uq_ai_settings_organization')
    )
    op.create_index(op.f('ix_ai_settings_organization_id'), 'ai_settings', ['organization_id'], unique=False)
    op.create_table('conversations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(title)) > 0', name=op.f('ck_conversations_title_not_blank')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_conversations_organization_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_conversations_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('organization_id', 'id', name='uq_conversations_org_id')
    )
    op.create_index('ix_conversations_org_user', 'conversations', ['organization_id', 'user_id', 'last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_organization_id'), 'conversations', ['organization_id'], unique=False)
    op.create_table('conversation_context',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'conversation_id'], ['conversations.organization_id', 'conversations.id'], name=op.f('fk_conversation_context_organization_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_conversation_context_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_context')),
    sa.UniqueConstraint('conversation_id', name='uq_conversation_context_conversation')
    )
    op.create_index(op.f('ix_conversation_context_organization_id'), 'conversation_context', ['organization_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=30), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('model_version_id', sa.Uuid(), nullable=True),
    sa.Column('sent_outside', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f('ck_conversation_messages_role_valid')),
    sa.ForeignKeyConstraint(['model_version_id'], ['ai_model_versions.id'], name=op.f('fk_conversation_messages_model_version_id_ai_model_versions')),
    sa.ForeignKeyConstraint(['organization_id', 'conversation_id'], ['conversations.organization_id', 'conversations.id'], name=op.f('fk_conversation_messages_organization_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_conversation_messages_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_messages')),
    sa.UniqueConstraint('organization_id', 'id', name='uq_conversation_messages_org_id')
    )
    op.create_index('ix_conversation_messages_conversation', 'conversation_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_conversation_messages_organization_id'), 'conversation_messages', ['organization_id'], unique=False)
    op.create_table('ai_tool_calls',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('tool', sa.String(length=40), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('facts', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'"), nullable=False),
    sa.Column('duration_ms', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'message_id'], ['conversation_messages.organization_id', 'conversation_messages.id'], name=op.f('fk_ai_tool_calls_organization_id_conversation_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_ai_tool_calls_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_tool_calls'))
    )
    op.create_index('ix_ai_tool_calls_message', 'ai_tool_calls', ['message_id'], unique=False)
    op.create_index(op.f('ix_ai_tool_calls_organization_id'), 'ai_tool_calls', ['organization_id'], unique=False)
    # The engine that answers without any outside provider: it is always there.
    op.execute(
        "INSERT INTO ai_model_versions (id, provider, model, version, description) VALUES "
        "(gen_random_uuid(), 'offline', 'vyterlix-grounded', '1', "
        "'Answers from the business''s own results using fixed rules. Nothing leaves Vyterlix.')"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_tool_calls_organization_id'), table_name='ai_tool_calls')
    op.drop_index('ix_ai_tool_calls_message', table_name='ai_tool_calls')
    op.drop_table('ai_tool_calls')
    op.drop_index(op.f('ix_conversation_messages_organization_id'), table_name='conversation_messages')
    op.drop_index('ix_conversation_messages_conversation', table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_conversation_context_organization_id'), table_name='conversation_context')
    op.drop_table('conversation_context')
    op.drop_index(op.f('ix_conversations_organization_id'), table_name='conversations')
    op.drop_index('ix_conversations_org_user', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_ai_settings_organization_id'), table_name='ai_settings')
    op.drop_table('ai_settings')
    op.drop_table('ai_model_versions')
    # ### end Alembic commands ###
