"""forecast accuracy columns

Revision ID: 8a249b9dff78
Revises: a3f9d1e60b24
Create Date: 2026-10-04 15:43:49.792765
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "8a249b9dff78"
down_revision: str | None = "a3f9d1e60b24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "forecast_evaluations", sa.Column("within_range", sa.SmallInteger(), nullable=True)
    )
    op.create_check_constraint(
        op.f("ck_forecast_evaluations_within_range_valid"),
        "forecast_evaluations",
        "within_range IS NULL OR within_range BETWEEN 0 AND n_points",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("ck_forecast_evaluations_within_range_valid"), "forecast_evaluations", type_="check"
    )
    op.drop_column("forecast_evaluations", "within_range")
    # ### end Alembic commands ###
